<?xml version="1.0" encoding="utf-8"?><Database Name="db_zscqTest" Class="DataTradeMarkDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=db_zscqTest;Persist Security Info=True;User ID=zscq" SettingsObjectName="zscq.Model.Properties.Settings" SettingsPropertyName="db_zscqConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.t_GoodsMainCategory" Member="t_GoodsMainCategory">
    <Type Name="t_GoodsMainCategory">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CategoryRemark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_GoodsDetailCategory" Member="t_GoodsDetailCategory">
    <Type Name="t_GoodsDetailCategory">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MainCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryRemark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Goods" Member="t_Goods">
    <Type Name="t_Goods">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DetailCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoodsCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GoodsRemark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="t_GoodsSearch">
    <Type Name="t_GoodsSearch">
      <Column Name="id" Type="System.Int32" CanBeNull="false" />
      <Column Name="DetailCategoryCode" Type="System.String" CanBeNull="false" />
      <Column Name="GoodsCode" Type="System.String" CanBeNull="false" />
      <Column Name="GoodsRemark" Type="System.String" CanBeNull="false" />
      <Column Name="MainCategoryCode" Type="System.String" CanBeNull="false" />
      <Column Name="MainCategoryID" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.t_NewTradeMarkStatus" Member="t_NewTradeMarkStatus">
    <Type Name="t_NewTradeMarkStatus">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StatusValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_GoodsCategoryFees" Member="t_GoodsCategoryFees">
    <Type Name="t_GoodsCategoryFees">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="i_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MainFees" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ItemNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExceedFees" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_NewTradeMarkRenewalDesc" Member="t_NewTradeMarkRenewalDesc">
    <Type Name="t_NewTradeMarkRenewalDesc">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WriteSample" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_NewTradeMarkMessage" Member="t_NewTradeMarkMessage">
    <Type Name="t_NewTradeMarkMessage">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TradeMarkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AddTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_NewTradeMark" Member="vw_NewTradeMark">
    <Type Name="vw_NewTradeMark">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="i_MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="i_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApplyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CardNoType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CardNoPDF" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Businesslicense" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CaseNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Is3D" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsColor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSound" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoundFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RegisteredNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApplyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PublicPreliminaryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RenewalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrademarkDescribeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrademarkDescribe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrademarkRemark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrademarkType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrademarkGoods" Type="System.String" DbType="NVarChar(800)" CanBeNull="true" />
      <Column Name="TrademarkPattern1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrademarkPattern2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrademarkRegBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ApplyBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AgentBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RenewalAgentBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RenewalApplyBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InputTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsReceiveEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RestDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nvc_UserNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="nvc_Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="nvc_OrderNum" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_NewTradeMarkRenewalInfo" Member="t_NewTradeMarkRenewalInfo">
    <Type Name="t_NewTradeMarkRenewalInfo">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TradeMarkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RenewalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsFinish" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_NewTradeMarkStatusDate" Member="t_NewTradeMarkStatusDate">
    <Type Name="t_NewTradeMarkStatusDate">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TradeMarkId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TradeMarkStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TradeMarkDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Apply" Member="t_Apply">
    <Type Name="t_Apply">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApplyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApplyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplyPinYin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApplyCardNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="provinceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MainQualificationPath" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CardNoPath" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_CaseNoOrder" Member="t_CaseNoOrder">
    <Type Name="t_CaseNoOrder">
      <Column Name="i_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SystemDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_NewTradeMarkInfo" Member="t_NewTradeMarkInfo">
    <Type Name="t_NewTradeMarkInfo">
      <Column Name="i_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="i_MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="i_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApplyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CardNoType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CardNoPDF" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Businesslicense" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CaseNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Is3D" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsColor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSound" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoundFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RegisteredNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApplyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PublicPreliminaryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RenewalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrademarkDescribeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrademarkDescribe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrademarkRemark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrademarkType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrademarkGoods" Type="System.String" DbType="NVarChar(800)" CanBeNull="true" />
      <Column Name="TrademarkMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TrademarkAgencyFee" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TrademarkLateFee" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TrademarkPattern1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrademarkPattern2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrademarkRegBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ApplyBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AgentBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ApplyUpBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AgentUpBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RenewalApplyBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RenewalAgentBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RenewalApplyUpBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RenewalAgentUpBook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InputTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsReceiveEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="i_SendEmail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="i_SendMessage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RestDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>