#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zscq.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_zscq")]
	public partial class DataOrderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_OrderOperateInfos(t_OrderOperateInfos instance);
    partial void Updatet_OrderOperateInfos(t_OrderOperateInfos instance);
    partial void Deletet_OrderOperateInfos(t_OrderOperateInfos instance);
    partial void Insertt_Orders(t_Orders instance);
    partial void Updatet_Orders(t_Orders instance);
    partial void Deletet_Orders(t_Orders instance);
    partial void Insertt_ReturnGoods(t_ReturnGoods instance);
    partial void Updatet_ReturnGoods(t_ReturnGoods instance);
    partial void Deletet_ReturnGoods(t_ReturnGoods instance);
    partial void Insertt_OrderDetails(t_OrderDetails instance);
    partial void Updatet_OrderDetails(t_OrderDetails instance);
    partial void Deletet_OrderDetails(t_OrderDetails instance);
    partial void Insertt_IntegralOrderDetails(t_IntegralOrderDetails instance);
    partial void Updatet_IntegralOrderDetails(t_IntegralOrderDetails instance);
    partial void Deletet_IntegralOrderDetails(t_IntegralOrderDetails instance);
    partial void Insertt_IntegralOrderOperateNote(t_IntegralOrderOperateNote instance);
    partial void Updatet_IntegralOrderOperateNote(t_IntegralOrderOperateNote instance);
    partial void Deletet_IntegralOrderOperateNote(t_IntegralOrderOperateNote instance);
    partial void Insertt_IntegralOrder(t_IntegralOrder instance);
    partial void Updatet_IntegralOrder(t_IntegralOrder instance);
    partial void Deletet_IntegralOrder(t_IntegralOrder instance);
    #endregion
		
		public DataOrderDataContext() : 
				base(global::zscq.Model.Properties.Settings.Default.db_zscqConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataOrderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataOrderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataOrderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataOrderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_OrderOperateInfos> t_OrderOperateInfos
		{
			get
			{
				return this.GetTable<t_OrderOperateInfos>();
			}
		}
		
		public System.Data.Linq.Table<t_Orders> t_Orders
		{
			get
			{
				return this.GetTable<t_Orders>();
			}
		}
		
		public System.Data.Linq.Table<t_ReturnGoods> t_ReturnGoods
		{
			get
			{
				return this.GetTable<t_ReturnGoods>();
			}
		}
		
		public System.Data.Linq.Table<t_OrderDetails> t_OrderDetails
		{
			get
			{
				return this.GetTable<t_OrderDetails>();
			}
		}
		
		public System.Data.Linq.Table<t_IntegralOrderDetails> t_IntegralOrderDetails
		{
			get
			{
				return this.GetTable<t_IntegralOrderDetails>();
			}
		}
		
		public System.Data.Linq.Table<t_IntegralOrderOperateNote> t_IntegralOrderOperateNote
		{
			get
			{
				return this.GetTable<t_IntegralOrderOperateNote>();
			}
		}
		
		public System.Data.Linq.Table<t_IntegralOrder> t_IntegralOrder
		{
			get
			{
				return this.GetTable<t_IntegralOrder>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_IntegralOrder_Delete")]
		public int pro_IntegralOrder_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_IntegralOrder_Delete")]
		public int pro_IntegralOrder_Delete1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> i_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), i_Id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_OrderOperateInfos")]
	public partial class t_OrderOperateInfos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private int _i_OrderId;
		
		private int _i_Type;
		
		private string _nvc_Info_1;
		
		private string _nvc_Info_2;
		
		private string _nvc_Info_3;
		
		private string _nvc_Info_4;
		
		private int _i_ManagerId;
		
		private System.DateTime _dt_AddTime;
		
		private EntityRef<t_Orders> _t_Orders;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Oni_OrderIdChanging(int value);
    partial void Oni_OrderIdChanged();
    partial void Oni_TypeChanging(int value);
    partial void Oni_TypeChanged();
    partial void Onnvc_Info_1Changing(string value);
    partial void Onnvc_Info_1Changed();
    partial void Onnvc_Info_2Changing(string value);
    partial void Onnvc_Info_2Changed();
    partial void Onnvc_Info_3Changing(string value);
    partial void Onnvc_Info_3Changed();
    partial void Onnvc_Info_4Changing(string value);
    partial void Onnvc_Info_4Changed();
    partial void Oni_ManagerIdChanging(int value);
    partial void Oni_ManagerIdChanged();
    partial void Ondt_AddTimeChanging(System.DateTime value);
    partial void Ondt_AddTimeChanged();
    #endregion
		
		public t_OrderOperateInfos()
		{
			this._t_Orders = default(EntityRef<t_Orders>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_OrderId", DbType="Int NOT NULL")]
		public int i_OrderId
		{
			get
			{
				return this._i_OrderId;
			}
			set
			{
				if ((this._i_OrderId != value))
				{
					if (this._t_Orders.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oni_OrderIdChanging(value);
					this.SendPropertyChanging();
					this._i_OrderId = value;
					this.SendPropertyChanged("i_OrderId");
					this.Oni_OrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Type", DbType="Int NOT NULL")]
		public int i_Type
		{
			get
			{
				return this._i_Type;
			}
			set
			{
				if ((this._i_Type != value))
				{
					this.Oni_TypeChanging(value);
					this.SendPropertyChanging();
					this._i_Type = value;
					this.SendPropertyChanged("i_Type");
					this.Oni_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Info_1", DbType="NVarChar(500)")]
		public string nvc_Info_1
		{
			get
			{
				return this._nvc_Info_1;
			}
			set
			{
				if ((this._nvc_Info_1 != value))
				{
					this.Onnvc_Info_1Changing(value);
					this.SendPropertyChanging();
					this._nvc_Info_1 = value;
					this.SendPropertyChanged("nvc_Info_1");
					this.Onnvc_Info_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Info_2", DbType="NVarChar(50)")]
		public string nvc_Info_2
		{
			get
			{
				return this._nvc_Info_2;
			}
			set
			{
				if ((this._nvc_Info_2 != value))
				{
					this.Onnvc_Info_2Changing(value);
					this.SendPropertyChanging();
					this._nvc_Info_2 = value;
					this.SendPropertyChanged("nvc_Info_2");
					this.Onnvc_Info_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Info_3", DbType="NVarChar(50)")]
		public string nvc_Info_3
		{
			get
			{
				return this._nvc_Info_3;
			}
			set
			{
				if ((this._nvc_Info_3 != value))
				{
					this.Onnvc_Info_3Changing(value);
					this.SendPropertyChanging();
					this._nvc_Info_3 = value;
					this.SendPropertyChanged("nvc_Info_3");
					this.Onnvc_Info_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Info_4", DbType="VarChar(50)")]
		public string nvc_Info_4
		{
			get
			{
				return this._nvc_Info_4;
			}
			set
			{
				if ((this._nvc_Info_4 != value))
				{
					this.Onnvc_Info_4Changing(value);
					this.SendPropertyChanging();
					this._nvc_Info_4 = value;
					this.SendPropertyChanged("nvc_Info_4");
					this.Onnvc_Info_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ManagerId", DbType="Int NOT NULL")]
		public int i_ManagerId
		{
			get
			{
				return this._i_ManagerId;
			}
			set
			{
				if ((this._i_ManagerId != value))
				{
					this.Oni_ManagerIdChanging(value);
					this.SendPropertyChanging();
					this._i_ManagerId = value;
					this.SendPropertyChanged("i_ManagerId");
					this.Oni_ManagerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Orders_t_OrderOperateInfos", Storage="_t_Orders", ThisKey="i_OrderId", OtherKey="i_Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public t_Orders t_Orders
		{
			get
			{
				return this._t_Orders.Entity;
			}
			set
			{
				t_Orders previousValue = this._t_Orders.Entity;
				if (((previousValue != value) 
							|| (this._t_Orders.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Orders.Entity = null;
						previousValue.t_OrderOperateInfos.Remove(this);
					}
					this._t_Orders.Entity = value;
					if ((value != null))
					{
						value.t_OrderOperateInfos.Add(this);
						this._i_OrderId = value.i_Id;
					}
					else
					{
						this._i_OrderId = default(int);
					}
					this.SendPropertyChanged("t_Orders");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Orders")]
	public partial class t_Orders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private string _nvc_OrderNumber;
		
		private int _i_MemberId;
		
		private int _Status;
		
		private System.DateTime _dt_AddTime;
		
		private decimal _dm_SumMoney;
		
		private decimal _dm_PSMoney;
		
		private decimal _dm_CouponMoney;
		
		private decimal _dm_IntegralMoney;
		
		private decimal _dm_MemberDiscountMoney;
		
		private decimal _dm_PromotionMoney;
		
		private string _nvc_PayWay;
		
		private string _nvc_PSWay;
		
		private string _nvc_PSTime;
		
		private int _i_PayStyle;
		
		private System.Nullable<System.DateTime> _dt_PayTime;
		
		private int _i_AddressId;
		
		private string _nvc_Address_Consignee;
		
		private int _i_Address_PId;
		
		private int _i_Address_CId;
		
		private int _i_Address_AId;
		
		private string _nvc_Address_StreetAddress;
		
		private string _nvc_Address_ZipCode;
		
		private string _nvc_Address_MobilePhone;
		
		private string _nvc_Address_TelPhone;
		
		private string _nvc_Address_Email;
		
		private int _i_Invoice;
		
		private int _i_InvoiceType;
		
		private string _nvc_InvoiceTitle;
		
		private string _nvc_Remarks;
		
		private int _i_DealerId;
		
		private int _i_AdminServer;
		
		private string _nvc_FOrderNumber;
		
		private string _nvc_SOrderNumber;
		
		private string _nvc_CouponRebateRules;
		
		private int _i_RebateIntegral;
		
		private int _i_RebatePlease;
		
		private int _i_OrderType;
		
		private string _nvc_Zengpin;
		
		private EntitySet<t_OrderOperateInfos> _t_OrderOperateInfos;
		
		private EntitySet<t_OrderDetails> _t_OrderDetails;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Onnvc_OrderNumberChanging(string value);
    partial void Onnvc_OrderNumberChanged();
    partial void Oni_MemberIdChanging(int value);
    partial void Oni_MemberIdChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void Ondt_AddTimeChanging(System.DateTime value);
    partial void Ondt_AddTimeChanged();
    partial void Ondm_SumMoneyChanging(decimal value);
    partial void Ondm_SumMoneyChanged();
    partial void Ondm_PSMoneyChanging(decimal value);
    partial void Ondm_PSMoneyChanged();
    partial void Ondm_CouponMoneyChanging(decimal value);
    partial void Ondm_CouponMoneyChanged();
    partial void Ondm_IntegralMoneyChanging(decimal value);
    partial void Ondm_IntegralMoneyChanged();
    partial void Ondm_MemberDiscountMoneyChanging(decimal value);
    partial void Ondm_MemberDiscountMoneyChanged();
    partial void Ondm_PromotionMoneyChanging(decimal value);
    partial void Ondm_PromotionMoneyChanged();
    partial void Onnvc_PayWayChanging(string value);
    partial void Onnvc_PayWayChanged();
    partial void Onnvc_PSWayChanging(string value);
    partial void Onnvc_PSWayChanged();
    partial void Onnvc_PSTimeChanging(string value);
    partial void Onnvc_PSTimeChanged();
    partial void Oni_PayStyleChanging(int value);
    partial void Oni_PayStyleChanged();
    partial void Ondt_PayTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_PayTimeChanged();
    partial void Oni_AddressIdChanging(int value);
    partial void Oni_AddressIdChanged();
    partial void Onnvc_Address_ConsigneeChanging(string value);
    partial void Onnvc_Address_ConsigneeChanged();
    partial void Oni_Address_PIdChanging(int value);
    partial void Oni_Address_PIdChanged();
    partial void Oni_Address_CIdChanging(int value);
    partial void Oni_Address_CIdChanged();
    partial void Oni_Address_AIdChanging(int value);
    partial void Oni_Address_AIdChanged();
    partial void Onnvc_Address_StreetAddressChanging(string value);
    partial void Onnvc_Address_StreetAddressChanged();
    partial void Onnvc_Address_ZipCodeChanging(string value);
    partial void Onnvc_Address_ZipCodeChanged();
    partial void Onnvc_Address_MobilePhoneChanging(string value);
    partial void Onnvc_Address_MobilePhoneChanged();
    partial void Onnvc_Address_TelPhoneChanging(string value);
    partial void Onnvc_Address_TelPhoneChanged();
    partial void Onnvc_Address_EmailChanging(string value);
    partial void Onnvc_Address_EmailChanged();
    partial void Oni_InvoiceChanging(int value);
    partial void Oni_InvoiceChanged();
    partial void Oni_InvoiceTypeChanging(int value);
    partial void Oni_InvoiceTypeChanged();
    partial void Onnvc_InvoiceTitleChanging(string value);
    partial void Onnvc_InvoiceTitleChanged();
    partial void Onnvc_RemarksChanging(string value);
    partial void Onnvc_RemarksChanged();
    partial void Oni_DealerIdChanging(int value);
    partial void Oni_DealerIdChanged();
    partial void Oni_AdminServerChanging(int value);
    partial void Oni_AdminServerChanged();
    partial void Onnvc_FOrderNumberChanging(string value);
    partial void Onnvc_FOrderNumberChanged();
    partial void Onnvc_SOrderNumberChanging(string value);
    partial void Onnvc_SOrderNumberChanged();
    partial void Onnvc_CouponRebateRulesChanging(string value);
    partial void Onnvc_CouponRebateRulesChanged();
    partial void Oni_RebateIntegralChanging(int value);
    partial void Oni_RebateIntegralChanged();
    partial void Oni_RebatePleaseChanging(int value);
    partial void Oni_RebatePleaseChanged();
    partial void Oni_OrderTypeChanging(int value);
    partial void Oni_OrderTypeChanged();
    partial void Onnvc_ZengpinChanging(string value);
    partial void Onnvc_ZengpinChanged();
    #endregion
		
		public t_Orders()
		{
			this._t_OrderOperateInfos = new EntitySet<t_OrderOperateInfos>(new Action<t_OrderOperateInfos>(this.attach_t_OrderOperateInfos), new Action<t_OrderOperateInfos>(this.detach_t_OrderOperateInfos));
			this._t_OrderDetails = new EntitySet<t_OrderDetails>(new Action<t_OrderDetails>(this.attach_t_OrderDetails), new Action<t_OrderDetails>(this.detach_t_OrderDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_OrderNumber", DbType="NVarChar(50)")]
		public string nvc_OrderNumber
		{
			get
			{
				return this._nvc_OrderNumber;
			}
			set
			{
				if ((this._nvc_OrderNumber != value))
				{
					this.Onnvc_OrderNumberChanging(value);
					this.SendPropertyChanging();
					this._nvc_OrderNumber = value;
					this.SendPropertyChanged("nvc_OrderNumber");
					this.Onnvc_OrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberId", DbType="Int NOT NULL")]
		public int i_MemberId
		{
			get
			{
				return this._i_MemberId;
			}
			set
			{
				if ((this._i_MemberId != value))
				{
					this.Oni_MemberIdChanging(value);
					this.SendPropertyChanging();
					this._i_MemberId = value;
					this.SendPropertyChanged("i_MemberId");
					this.Oni_MemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_SumMoney", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_SumMoney
		{
			get
			{
				return this._dm_SumMoney;
			}
			set
			{
				if ((this._dm_SumMoney != value))
				{
					this.Ondm_SumMoneyChanging(value);
					this.SendPropertyChanging();
					this._dm_SumMoney = value;
					this.SendPropertyChanged("dm_SumMoney");
					this.Ondm_SumMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_PSMoney", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_PSMoney
		{
			get
			{
				return this._dm_PSMoney;
			}
			set
			{
				if ((this._dm_PSMoney != value))
				{
					this.Ondm_PSMoneyChanging(value);
					this.SendPropertyChanging();
					this._dm_PSMoney = value;
					this.SendPropertyChanged("dm_PSMoney");
					this.Ondm_PSMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_CouponMoney", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_CouponMoney
		{
			get
			{
				return this._dm_CouponMoney;
			}
			set
			{
				if ((this._dm_CouponMoney != value))
				{
					this.Ondm_CouponMoneyChanging(value);
					this.SendPropertyChanging();
					this._dm_CouponMoney = value;
					this.SendPropertyChanged("dm_CouponMoney");
					this.Ondm_CouponMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_IntegralMoney", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_IntegralMoney
		{
			get
			{
				return this._dm_IntegralMoney;
			}
			set
			{
				if ((this._dm_IntegralMoney != value))
				{
					this.Ondm_IntegralMoneyChanging(value);
					this.SendPropertyChanging();
					this._dm_IntegralMoney = value;
					this.SendPropertyChanged("dm_IntegralMoney");
					this.Ondm_IntegralMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_MemberDiscountMoney", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_MemberDiscountMoney
		{
			get
			{
				return this._dm_MemberDiscountMoney;
			}
			set
			{
				if ((this._dm_MemberDiscountMoney != value))
				{
					this.Ondm_MemberDiscountMoneyChanging(value);
					this.SendPropertyChanging();
					this._dm_MemberDiscountMoney = value;
					this.SendPropertyChanged("dm_MemberDiscountMoney");
					this.Ondm_MemberDiscountMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_PromotionMoney", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_PromotionMoney
		{
			get
			{
				return this._dm_PromotionMoney;
			}
			set
			{
				if ((this._dm_PromotionMoney != value))
				{
					this.Ondm_PromotionMoneyChanging(value);
					this.SendPropertyChanging();
					this._dm_PromotionMoney = value;
					this.SendPropertyChanged("dm_PromotionMoney");
					this.Ondm_PromotionMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_PayWay", DbType="NVarChar(50)")]
		public string nvc_PayWay
		{
			get
			{
				return this._nvc_PayWay;
			}
			set
			{
				if ((this._nvc_PayWay != value))
				{
					this.Onnvc_PayWayChanging(value);
					this.SendPropertyChanging();
					this._nvc_PayWay = value;
					this.SendPropertyChanged("nvc_PayWay");
					this.Onnvc_PayWayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_PSWay", DbType="NVarChar(50)")]
		public string nvc_PSWay
		{
			get
			{
				return this._nvc_PSWay;
			}
			set
			{
				if ((this._nvc_PSWay != value))
				{
					this.Onnvc_PSWayChanging(value);
					this.SendPropertyChanging();
					this._nvc_PSWay = value;
					this.SendPropertyChanged("nvc_PSWay");
					this.Onnvc_PSWayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_PSTime", DbType="NVarChar(50)")]
		public string nvc_PSTime
		{
			get
			{
				return this._nvc_PSTime;
			}
			set
			{
				if ((this._nvc_PSTime != value))
				{
					this.Onnvc_PSTimeChanging(value);
					this.SendPropertyChanging();
					this._nvc_PSTime = value;
					this.SendPropertyChanged("nvc_PSTime");
					this.Onnvc_PSTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_PayStyle", DbType="Int NOT NULL")]
		public int i_PayStyle
		{
			get
			{
				return this._i_PayStyle;
			}
			set
			{
				if ((this._i_PayStyle != value))
				{
					this.Oni_PayStyleChanging(value);
					this.SendPropertyChanging();
					this._i_PayStyle = value;
					this.SendPropertyChanged("i_PayStyle");
					this.Oni_PayStyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_PayTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_PayTime
		{
			get
			{
				return this._dt_PayTime;
			}
			set
			{
				if ((this._dt_PayTime != value))
				{
					this.Ondt_PayTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_PayTime = value;
					this.SendPropertyChanged("dt_PayTime");
					this.Ondt_PayTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_AddressId", DbType="Int NOT NULL")]
		public int i_AddressId
		{
			get
			{
				return this._i_AddressId;
			}
			set
			{
				if ((this._i_AddressId != value))
				{
					this.Oni_AddressIdChanging(value);
					this.SendPropertyChanging();
					this._i_AddressId = value;
					this.SendPropertyChanged("i_AddressId");
					this.Oni_AddressIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_Consignee", DbType="NVarChar(50)")]
		public string nvc_Address_Consignee
		{
			get
			{
				return this._nvc_Address_Consignee;
			}
			set
			{
				if ((this._nvc_Address_Consignee != value))
				{
					this.Onnvc_Address_ConsigneeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_Consignee = value;
					this.SendPropertyChanged("nvc_Address_Consignee");
					this.Onnvc_Address_ConsigneeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Address_PId", DbType="Int NOT NULL")]
		public int i_Address_PId
		{
			get
			{
				return this._i_Address_PId;
			}
			set
			{
				if ((this._i_Address_PId != value))
				{
					this.Oni_Address_PIdChanging(value);
					this.SendPropertyChanging();
					this._i_Address_PId = value;
					this.SendPropertyChanged("i_Address_PId");
					this.Oni_Address_PIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Address_CId", DbType="Int NOT NULL")]
		public int i_Address_CId
		{
			get
			{
				return this._i_Address_CId;
			}
			set
			{
				if ((this._i_Address_CId != value))
				{
					this.Oni_Address_CIdChanging(value);
					this.SendPropertyChanging();
					this._i_Address_CId = value;
					this.SendPropertyChanged("i_Address_CId");
					this.Oni_Address_CIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Address_AId", DbType="Int NOT NULL")]
		public int i_Address_AId
		{
			get
			{
				return this._i_Address_AId;
			}
			set
			{
				if ((this._i_Address_AId != value))
				{
					this.Oni_Address_AIdChanging(value);
					this.SendPropertyChanging();
					this._i_Address_AId = value;
					this.SendPropertyChanged("i_Address_AId");
					this.Oni_Address_AIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_StreetAddress", DbType="NVarChar(500)")]
		public string nvc_Address_StreetAddress
		{
			get
			{
				return this._nvc_Address_StreetAddress;
			}
			set
			{
				if ((this._nvc_Address_StreetAddress != value))
				{
					this.Onnvc_Address_StreetAddressChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_StreetAddress = value;
					this.SendPropertyChanged("nvc_Address_StreetAddress");
					this.Onnvc_Address_StreetAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_ZipCode", DbType="VarChar(6)")]
		public string nvc_Address_ZipCode
		{
			get
			{
				return this._nvc_Address_ZipCode;
			}
			set
			{
				if ((this._nvc_Address_ZipCode != value))
				{
					this.Onnvc_Address_ZipCodeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_ZipCode = value;
					this.SendPropertyChanged("nvc_Address_ZipCode");
					this.Onnvc_Address_ZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_MobilePhone", DbType="VarChar(50)")]
		public string nvc_Address_MobilePhone
		{
			get
			{
				return this._nvc_Address_MobilePhone;
			}
			set
			{
				if ((this._nvc_Address_MobilePhone != value))
				{
					this.Onnvc_Address_MobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_MobilePhone = value;
					this.SendPropertyChanged("nvc_Address_MobilePhone");
					this.Onnvc_Address_MobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_TelPhone", DbType="VarChar(50)")]
		public string nvc_Address_TelPhone
		{
			get
			{
				return this._nvc_Address_TelPhone;
			}
			set
			{
				if ((this._nvc_Address_TelPhone != value))
				{
					this.Onnvc_Address_TelPhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_TelPhone = value;
					this.SendPropertyChanged("nvc_Address_TelPhone");
					this.Onnvc_Address_TelPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_Email", DbType="VarChar(50)")]
		public string nvc_Address_Email
		{
			get
			{
				return this._nvc_Address_Email;
			}
			set
			{
				if ((this._nvc_Address_Email != value))
				{
					this.Onnvc_Address_EmailChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_Email = value;
					this.SendPropertyChanged("nvc_Address_Email");
					this.Onnvc_Address_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Invoice", DbType="Int NOT NULL")]
		public int i_Invoice
		{
			get
			{
				return this._i_Invoice;
			}
			set
			{
				if ((this._i_Invoice != value))
				{
					this.Oni_InvoiceChanging(value);
					this.SendPropertyChanging();
					this._i_Invoice = value;
					this.SendPropertyChanged("i_Invoice");
					this.Oni_InvoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_InvoiceType", DbType="Int NOT NULL")]
		public int i_InvoiceType
		{
			get
			{
				return this._i_InvoiceType;
			}
			set
			{
				if ((this._i_InvoiceType != value))
				{
					this.Oni_InvoiceTypeChanging(value);
					this.SendPropertyChanging();
					this._i_InvoiceType = value;
					this.SendPropertyChanged("i_InvoiceType");
					this.Oni_InvoiceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_InvoiceTitle", DbType="NVarChar(50)")]
		public string nvc_InvoiceTitle
		{
			get
			{
				return this._nvc_InvoiceTitle;
			}
			set
			{
				if ((this._nvc_InvoiceTitle != value))
				{
					this.Onnvc_InvoiceTitleChanging(value);
					this.SendPropertyChanging();
					this._nvc_InvoiceTitle = value;
					this.SendPropertyChanged("nvc_InvoiceTitle");
					this.Onnvc_InvoiceTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Remarks", DbType="NVarChar(500)")]
		public string nvc_Remarks
		{
			get
			{
				return this._nvc_Remarks;
			}
			set
			{
				if ((this._nvc_Remarks != value))
				{
					this.Onnvc_RemarksChanging(value);
					this.SendPropertyChanging();
					this._nvc_Remarks = value;
					this.SendPropertyChanged("nvc_Remarks");
					this.Onnvc_RemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_DealerId", DbType="Int NOT NULL")]
		public int i_DealerId
		{
			get
			{
				return this._i_DealerId;
			}
			set
			{
				if ((this._i_DealerId != value))
				{
					this.Oni_DealerIdChanging(value);
					this.SendPropertyChanging();
					this._i_DealerId = value;
					this.SendPropertyChanged("i_DealerId");
					this.Oni_DealerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_AdminServer", DbType="Int NOT NULL")]
		public int i_AdminServer
		{
			get
			{
				return this._i_AdminServer;
			}
			set
			{
				if ((this._i_AdminServer != value))
				{
					this.Oni_AdminServerChanging(value);
					this.SendPropertyChanging();
					this._i_AdminServer = value;
					this.SendPropertyChanged("i_AdminServer");
					this.Oni_AdminServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_FOrderNumber", DbType="NVarChar(50)")]
		public string nvc_FOrderNumber
		{
			get
			{
				return this._nvc_FOrderNumber;
			}
			set
			{
				if ((this._nvc_FOrderNumber != value))
				{
					this.Onnvc_FOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._nvc_FOrderNumber = value;
					this.SendPropertyChanged("nvc_FOrderNumber");
					this.Onnvc_FOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_SOrderNumber", DbType="NVarChar(500)")]
		public string nvc_SOrderNumber
		{
			get
			{
				return this._nvc_SOrderNumber;
			}
			set
			{
				if ((this._nvc_SOrderNumber != value))
				{
					this.Onnvc_SOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._nvc_SOrderNumber = value;
					this.SendPropertyChanged("nvc_SOrderNumber");
					this.Onnvc_SOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_CouponRebateRules", DbType="NVarChar(500)")]
		public string nvc_CouponRebateRules
		{
			get
			{
				return this._nvc_CouponRebateRules;
			}
			set
			{
				if ((this._nvc_CouponRebateRules != value))
				{
					this.Onnvc_CouponRebateRulesChanging(value);
					this.SendPropertyChanging();
					this._nvc_CouponRebateRules = value;
					this.SendPropertyChanged("nvc_CouponRebateRules");
					this.Onnvc_CouponRebateRulesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_RebateIntegral", DbType="Int NOT NULL")]
		public int i_RebateIntegral
		{
			get
			{
				return this._i_RebateIntegral;
			}
			set
			{
				if ((this._i_RebateIntegral != value))
				{
					this.Oni_RebateIntegralChanging(value);
					this.SendPropertyChanging();
					this._i_RebateIntegral = value;
					this.SendPropertyChanged("i_RebateIntegral");
					this.Oni_RebateIntegralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_RebatePlease", DbType="Int NOT NULL")]
		public int i_RebatePlease
		{
			get
			{
				return this._i_RebatePlease;
			}
			set
			{
				if ((this._i_RebatePlease != value))
				{
					this.Oni_RebatePleaseChanging(value);
					this.SendPropertyChanging();
					this._i_RebatePlease = value;
					this.SendPropertyChanged("i_RebatePlease");
					this.Oni_RebatePleaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_OrderType", DbType="Int NOT NULL")]
		public int i_OrderType
		{
			get
			{
				return this._i_OrderType;
			}
			set
			{
				if ((this._i_OrderType != value))
				{
					this.Oni_OrderTypeChanging(value);
					this.SendPropertyChanging();
					this._i_OrderType = value;
					this.SendPropertyChanged("i_OrderType");
					this.Oni_OrderTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Zengpin", DbType="NVarChar(150)")]
		public string nvc_Zengpin
		{
			get
			{
				return this._nvc_Zengpin;
			}
			set
			{
				if ((this._nvc_Zengpin != value))
				{
					this.Onnvc_ZengpinChanging(value);
					this.SendPropertyChanging();
					this._nvc_Zengpin = value;
					this.SendPropertyChanged("nvc_Zengpin");
					this.Onnvc_ZengpinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Orders_t_OrderOperateInfos", Storage="_t_OrderOperateInfos", ThisKey="i_Id", OtherKey="i_OrderId")]
		public EntitySet<t_OrderOperateInfos> t_OrderOperateInfos
		{
			get
			{
				return this._t_OrderOperateInfos;
			}
			set
			{
				this._t_OrderOperateInfos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Orders_t_OrderDetails", Storage="_t_OrderDetails", ThisKey="i_Id", OtherKey="i_OrderId")]
		public EntitySet<t_OrderDetails> t_OrderDetails
		{
			get
			{
				return this._t_OrderDetails;
			}
			set
			{
				this._t_OrderDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_t_OrderOperateInfos(t_OrderOperateInfos entity)
		{
			this.SendPropertyChanging();
			entity.t_Orders = this;
		}
		
		private void detach_t_OrderOperateInfos(t_OrderOperateInfos entity)
		{
			this.SendPropertyChanging();
			entity.t_Orders = null;
		}
		
		private void attach_t_OrderDetails(t_OrderDetails entity)
		{
			this.SendPropertyChanging();
			entity.t_Orders = this;
		}
		
		private void detach_t_OrderDetails(t_OrderDetails entity)
		{
			this.SendPropertyChanging();
			entity.t_Orders = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_ReturnGoods")]
	public partial class t_ReturnGoods : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private int _i_DetailsId;
		
		private int _i_MemberId;
		
		private int _i_State;
		
		private int _i_Number;
		
		private string _nvc_Reason;
		
		private System.DateTime _dt_AddTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Oni_DetailsIdChanging(int value);
    partial void Oni_DetailsIdChanged();
    partial void Oni_MemberIdChanging(int value);
    partial void Oni_MemberIdChanged();
    partial void Oni_StateChanging(int value);
    partial void Oni_StateChanged();
    partial void Oni_NumberChanging(int value);
    partial void Oni_NumberChanged();
    partial void Onnvc_ReasonChanging(string value);
    partial void Onnvc_ReasonChanged();
    partial void Ondt_AddTimeChanging(System.DateTime value);
    partial void Ondt_AddTimeChanged();
    #endregion
		
		public t_ReturnGoods()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_DetailsId", DbType="Int NOT NULL")]
		public int i_DetailsId
		{
			get
			{
				return this._i_DetailsId;
			}
			set
			{
				if ((this._i_DetailsId != value))
				{
					this.Oni_DetailsIdChanging(value);
					this.SendPropertyChanging();
					this._i_DetailsId = value;
					this.SendPropertyChanged("i_DetailsId");
					this.Oni_DetailsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberId", DbType="Int NOT NULL")]
		public int i_MemberId
		{
			get
			{
				return this._i_MemberId;
			}
			set
			{
				if ((this._i_MemberId != value))
				{
					this.Oni_MemberIdChanging(value);
					this.SendPropertyChanging();
					this._i_MemberId = value;
					this.SendPropertyChanged("i_MemberId");
					this.Oni_MemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_State", DbType="Int NOT NULL")]
		public int i_State
		{
			get
			{
				return this._i_State;
			}
			set
			{
				if ((this._i_State != value))
				{
					this.Oni_StateChanging(value);
					this.SendPropertyChanging();
					this._i_State = value;
					this.SendPropertyChanged("i_State");
					this.Oni_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Number", DbType="Int NOT NULL")]
		public int i_Number
		{
			get
			{
				return this._i_Number;
			}
			set
			{
				if ((this._i_Number != value))
				{
					this.Oni_NumberChanging(value);
					this.SendPropertyChanging();
					this._i_Number = value;
					this.SendPropertyChanged("i_Number");
					this.Oni_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Reason", DbType="NVarChar(500)")]
		public string nvc_Reason
		{
			get
			{
				return this._nvc_Reason;
			}
			set
			{
				if ((this._nvc_Reason != value))
				{
					this.Onnvc_ReasonChanging(value);
					this.SendPropertyChanging();
					this._nvc_Reason = value;
					this.SendPropertyChanged("nvc_Reason");
					this.Onnvc_ReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_OrderDetails")]
	public partial class t_OrderDetails : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private int _i_OrderId;
		
		private int _i_ProductId;
		
		private int _i_Number;
		
		private decimal _dm_Price;
		
		private int _i_ProductType;
		
		private int _i_Comment;
		
		private int _i_Integral;
		
		private int _i_Suoju;
		
		private int _i_GuigeValue;
		
		private int _i_GuigeContent;
		
		private EntityRef<t_Orders> _t_Orders;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Oni_OrderIdChanging(int value);
    partial void Oni_OrderIdChanged();
    partial void Oni_ProductIdChanging(int value);
    partial void Oni_ProductIdChanged();
    partial void Oni_NumberChanging(int value);
    partial void Oni_NumberChanged();
    partial void Ondm_PriceChanging(decimal value);
    partial void Ondm_PriceChanged();
    partial void Oni_ProductTypeChanging(int value);
    partial void Oni_ProductTypeChanged();
    partial void Oni_CommentChanging(int value);
    partial void Oni_CommentChanged();
    partial void Oni_IntegralChanging(int value);
    partial void Oni_IntegralChanged();
    partial void Oni_SuojuChanging(int value);
    partial void Oni_SuojuChanged();
    partial void Oni_GuigeValueChanging(int value);
    partial void Oni_GuigeValueChanged();
    partial void Oni_GuigeContentChanging(int value);
    partial void Oni_GuigeContentChanged();
    #endregion
		
		public t_OrderDetails()
		{
			this._t_Orders = default(EntityRef<t_Orders>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_OrderId", DbType="Int NOT NULL")]
		public int i_OrderId
		{
			get
			{
				return this._i_OrderId;
			}
			set
			{
				if ((this._i_OrderId != value))
				{
					if (this._t_Orders.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oni_OrderIdChanging(value);
					this.SendPropertyChanging();
					this._i_OrderId = value;
					this.SendPropertyChanged("i_OrderId");
					this.Oni_OrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ProductId", DbType="Int NOT NULL")]
		public int i_ProductId
		{
			get
			{
				return this._i_ProductId;
			}
			set
			{
				if ((this._i_ProductId != value))
				{
					this.Oni_ProductIdChanging(value);
					this.SendPropertyChanging();
					this._i_ProductId = value;
					this.SendPropertyChanged("i_ProductId");
					this.Oni_ProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Number", DbType="Int NOT NULL")]
		public int i_Number
		{
			get
			{
				return this._i_Number;
			}
			set
			{
				if ((this._i_Number != value))
				{
					this.Oni_NumberChanging(value);
					this.SendPropertyChanging();
					this._i_Number = value;
					this.SendPropertyChanged("i_Number");
					this.Oni_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_Price", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_Price
		{
			get
			{
				return this._dm_Price;
			}
			set
			{
				if ((this._dm_Price != value))
				{
					this.Ondm_PriceChanging(value);
					this.SendPropertyChanging();
					this._dm_Price = value;
					this.SendPropertyChanged("dm_Price");
					this.Ondm_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ProductType", DbType="Int NOT NULL")]
		public int i_ProductType
		{
			get
			{
				return this._i_ProductType;
			}
			set
			{
				if ((this._i_ProductType != value))
				{
					this.Oni_ProductTypeChanging(value);
					this.SendPropertyChanging();
					this._i_ProductType = value;
					this.SendPropertyChanged("i_ProductType");
					this.Oni_ProductTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Comment", DbType="Int NOT NULL")]
		public int i_Comment
		{
			get
			{
				return this._i_Comment;
			}
			set
			{
				if ((this._i_Comment != value))
				{
					this.Oni_CommentChanging(value);
					this.SendPropertyChanging();
					this._i_Comment = value;
					this.SendPropertyChanged("i_Comment");
					this.Oni_CommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Integral", DbType="Int NOT NULL")]
		public int i_Integral
		{
			get
			{
				return this._i_Integral;
			}
			set
			{
				if ((this._i_Integral != value))
				{
					this.Oni_IntegralChanging(value);
					this.SendPropertyChanging();
					this._i_Integral = value;
					this.SendPropertyChanged("i_Integral");
					this.Oni_IntegralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Suoju", DbType="Int NOT NULL")]
		public int i_Suoju
		{
			get
			{
				return this._i_Suoju;
			}
			set
			{
				if ((this._i_Suoju != value))
				{
					this.Oni_SuojuChanging(value);
					this.SendPropertyChanging();
					this._i_Suoju = value;
					this.SendPropertyChanged("i_Suoju");
					this.Oni_SuojuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_GuigeValue", DbType="Int NOT NULL")]
		public int i_GuigeValue
		{
			get
			{
				return this._i_GuigeValue;
			}
			set
			{
				if ((this._i_GuigeValue != value))
				{
					this.Oni_GuigeValueChanging(value);
					this.SendPropertyChanging();
					this._i_GuigeValue = value;
					this.SendPropertyChanged("i_GuigeValue");
					this.Oni_GuigeValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_GuigeContent", DbType="Int NOT NULL")]
		public int i_GuigeContent
		{
			get
			{
				return this._i_GuigeContent;
			}
			set
			{
				if ((this._i_GuigeContent != value))
				{
					this.Oni_GuigeContentChanging(value);
					this.SendPropertyChanging();
					this._i_GuigeContent = value;
					this.SendPropertyChanged("i_GuigeContent");
					this.Oni_GuigeContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Orders_t_OrderDetails", Storage="_t_Orders", ThisKey="i_OrderId", OtherKey="i_Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public t_Orders t_Orders
		{
			get
			{
				return this._t_Orders.Entity;
			}
			set
			{
				t_Orders previousValue = this._t_Orders.Entity;
				if (((previousValue != value) 
							|| (this._t_Orders.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Orders.Entity = null;
						previousValue.t_OrderDetails.Remove(this);
					}
					this._t_Orders.Entity = value;
					if ((value != null))
					{
						value.t_OrderDetails.Add(this);
						this._i_OrderId = value.i_Id;
					}
					else
					{
						this._i_OrderId = default(int);
					}
					this.SendPropertyChanged("t_Orders");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_IntegralOrderDetails")]
	public partial class t_IntegralOrderDetails : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private int _i_IntegralOrderId;
		
		private int _i_IntegralProductId;
		
		private int _i_BuyNumber;
		
		private int _i_Integral;
		
		private int _i_IntegralProductType;
		
		private int _i_IntegralMobileId;
		
		private EntityRef<t_IntegralOrder> _t_IntegralOrder;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Oni_IntegralOrderIdChanging(int value);
    partial void Oni_IntegralOrderIdChanged();
    partial void Oni_IntegralProductIdChanging(int value);
    partial void Oni_IntegralProductIdChanged();
    partial void Oni_BuyNumberChanging(int value);
    partial void Oni_BuyNumberChanged();
    partial void Oni_IntegralChanging(int value);
    partial void Oni_IntegralChanged();
    partial void Oni_IntegralProductTypeChanging(int value);
    partial void Oni_IntegralProductTypeChanged();
    partial void Oni_IntegralMobileIdChanging(int value);
    partial void Oni_IntegralMobileIdChanged();
    #endregion
		
		public t_IntegralOrderDetails()
		{
			this._t_IntegralOrder = default(EntityRef<t_IntegralOrder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralOrderId", DbType="Int NOT NULL")]
		public int i_IntegralOrderId
		{
			get
			{
				return this._i_IntegralOrderId;
			}
			set
			{
				if ((this._i_IntegralOrderId != value))
				{
					if (this._t_IntegralOrder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oni_IntegralOrderIdChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralOrderId = value;
					this.SendPropertyChanged("i_IntegralOrderId");
					this.Oni_IntegralOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralProductId", DbType="Int NOT NULL")]
		public int i_IntegralProductId
		{
			get
			{
				return this._i_IntegralProductId;
			}
			set
			{
				if ((this._i_IntegralProductId != value))
				{
					this.Oni_IntegralProductIdChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralProductId = value;
					this.SendPropertyChanged("i_IntegralProductId");
					this.Oni_IntegralProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_BuyNumber", DbType="Int NOT NULL")]
		public int i_BuyNumber
		{
			get
			{
				return this._i_BuyNumber;
			}
			set
			{
				if ((this._i_BuyNumber != value))
				{
					this.Oni_BuyNumberChanging(value);
					this.SendPropertyChanging();
					this._i_BuyNumber = value;
					this.SendPropertyChanged("i_BuyNumber");
					this.Oni_BuyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Integral", DbType="Int NOT NULL")]
		public int i_Integral
		{
			get
			{
				return this._i_Integral;
			}
			set
			{
				if ((this._i_Integral != value))
				{
					this.Oni_IntegralChanging(value);
					this.SendPropertyChanging();
					this._i_Integral = value;
					this.SendPropertyChanged("i_Integral");
					this.Oni_IntegralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralProductType", DbType="Int NOT NULL")]
		public int i_IntegralProductType
		{
			get
			{
				return this._i_IntegralProductType;
			}
			set
			{
				if ((this._i_IntegralProductType != value))
				{
					this.Oni_IntegralProductTypeChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralProductType = value;
					this.SendPropertyChanged("i_IntegralProductType");
					this.Oni_IntegralProductTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralMobileId", DbType="Int NOT NULL")]
		public int i_IntegralMobileId
		{
			get
			{
				return this._i_IntegralMobileId;
			}
			set
			{
				if ((this._i_IntegralMobileId != value))
				{
					this.Oni_IntegralMobileIdChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralMobileId = value;
					this.SendPropertyChanged("i_IntegralMobileId");
					this.Oni_IntegralMobileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_IntegralOrder_t_IntegralOrderDetails", Storage="_t_IntegralOrder", ThisKey="i_IntegralOrderId", OtherKey="i_Id", IsForeignKey=true)]
		public t_IntegralOrder t_IntegralOrder
		{
			get
			{
				return this._t_IntegralOrder.Entity;
			}
			set
			{
				t_IntegralOrder previousValue = this._t_IntegralOrder.Entity;
				if (((previousValue != value) 
							|| (this._t_IntegralOrder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_IntegralOrder.Entity = null;
						previousValue.t_IntegralOrderDetails.Remove(this);
					}
					this._t_IntegralOrder.Entity = value;
					if ((value != null))
					{
						value.t_IntegralOrderDetails.Add(this);
						this._i_IntegralOrderId = value.i_Id;
					}
					else
					{
						this._i_IntegralOrderId = default(int);
					}
					this.SendPropertyChanged("t_IntegralOrder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_IntegralOrderOperateNote")]
	public partial class t_IntegralOrderOperateNote : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private int _i_OrderId;
		
		private string _nvc_Type;
		
		private string _nvc_Remark;
		
		private int _i_ManagerId;
		
		private System.DateTime _dt_AddTime;
		
		private EntityRef<t_IntegralOrder> _t_IntegralOrder;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Oni_OrderIdChanging(int value);
    partial void Oni_OrderIdChanged();
    partial void Onnvc_TypeChanging(string value);
    partial void Onnvc_TypeChanged();
    partial void Onnvc_RemarkChanging(string value);
    partial void Onnvc_RemarkChanged();
    partial void Oni_ManagerIdChanging(int value);
    partial void Oni_ManagerIdChanged();
    partial void Ondt_AddTimeChanging(System.DateTime value);
    partial void Ondt_AddTimeChanged();
    #endregion
		
		public t_IntegralOrderOperateNote()
		{
			this._t_IntegralOrder = default(EntityRef<t_IntegralOrder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_OrderId", DbType="Int NOT NULL")]
		public int i_OrderId
		{
			get
			{
				return this._i_OrderId;
			}
			set
			{
				if ((this._i_OrderId != value))
				{
					if (this._t_IntegralOrder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oni_OrderIdChanging(value);
					this.SendPropertyChanging();
					this._i_OrderId = value;
					this.SendPropertyChanged("i_OrderId");
					this.Oni_OrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Type", DbType="NVarChar(50)")]
		public string nvc_Type
		{
			get
			{
				return this._nvc_Type;
			}
			set
			{
				if ((this._nvc_Type != value))
				{
					this.Onnvc_TypeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Type = value;
					this.SendPropertyChanged("nvc_Type");
					this.Onnvc_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Remark", DbType="NVarChar(500)")]
		public string nvc_Remark
		{
			get
			{
				return this._nvc_Remark;
			}
			set
			{
				if ((this._nvc_Remark != value))
				{
					this.Onnvc_RemarkChanging(value);
					this.SendPropertyChanging();
					this._nvc_Remark = value;
					this.SendPropertyChanged("nvc_Remark");
					this.Onnvc_RemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ManagerId", DbType="Int NOT NULL")]
		public int i_ManagerId
		{
			get
			{
				return this._i_ManagerId;
			}
			set
			{
				if ((this._i_ManagerId != value))
				{
					this.Oni_ManagerIdChanging(value);
					this.SendPropertyChanging();
					this._i_ManagerId = value;
					this.SendPropertyChanged("i_ManagerId");
					this.Oni_ManagerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_IntegralOrder_t_IntegralOrderOperateNote", Storage="_t_IntegralOrder", ThisKey="i_OrderId", OtherKey="i_Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public t_IntegralOrder t_IntegralOrder
		{
			get
			{
				return this._t_IntegralOrder.Entity;
			}
			set
			{
				t_IntegralOrder previousValue = this._t_IntegralOrder.Entity;
				if (((previousValue != value) 
							|| (this._t_IntegralOrder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_IntegralOrder.Entity = null;
						previousValue.t_IntegralOrderOperateNote.Remove(this);
					}
					this._t_IntegralOrder.Entity = value;
					if ((value != null))
					{
						value.t_IntegralOrderOperateNote.Add(this);
						this._i_OrderId = value.i_Id;
					}
					else
					{
						this._i_OrderId = default(int);
					}
					this.SendPropertyChanged("t_IntegralOrder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_IntegralOrder")]
	public partial class t_IntegralOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private string _nvc_OrderNumber;
		
		private int _i_MemberId;
		
		private int _i_State;
		
		private System.DateTime _dt_AddTime;
		
		private int _i_SumIntegral;
		
		private string _nvc_PSWay;
		
		private int _i_IntegralProductId;
		
		private int _i_BuyNumber;
		
		private int _i_AddressId;
		
		private string _nvc_Address_Consignee;
		
		private int _i_Address_GId;
		
		private int _i_Address_PId;
		
		private int _i_Address_CId;
		
		private int _i_Address_AId;
		
		private string _nvc_Address_StreetAddress;
		
		private string _nvc_Address_ZipCode;
		
		private string _nvc_Address_MobilePhone;
		
		private string _nvc_Address_TelPhone;
		
		private string _nvc_Address_Email;
		
		private int _i_IntegralMobileId;
		
		private EntitySet<t_IntegralOrderDetails> _t_IntegralOrderDetails;
		
		private EntitySet<t_IntegralOrderOperateNote> _t_IntegralOrderOperateNote;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Onnvc_OrderNumberChanging(string value);
    partial void Onnvc_OrderNumberChanged();
    partial void Oni_MemberIdChanging(int value);
    partial void Oni_MemberIdChanged();
    partial void Oni_StateChanging(int value);
    partial void Oni_StateChanged();
    partial void Ondt_AddTimeChanging(System.DateTime value);
    partial void Ondt_AddTimeChanged();
    partial void Oni_SumIntegralChanging(int value);
    partial void Oni_SumIntegralChanged();
    partial void Onnvc_PSWayChanging(string value);
    partial void Onnvc_PSWayChanged();
    partial void Oni_IntegralProductIdChanging(int value);
    partial void Oni_IntegralProductIdChanged();
    partial void Oni_BuyNumberChanging(int value);
    partial void Oni_BuyNumberChanged();
    partial void Oni_AddressIdChanging(int value);
    partial void Oni_AddressIdChanged();
    partial void Onnvc_Address_ConsigneeChanging(string value);
    partial void Onnvc_Address_ConsigneeChanged();
    partial void Oni_Address_GIdChanging(int value);
    partial void Oni_Address_GIdChanged();
    partial void Oni_Address_PIdChanging(int value);
    partial void Oni_Address_PIdChanged();
    partial void Oni_Address_CIdChanging(int value);
    partial void Oni_Address_CIdChanged();
    partial void Oni_Address_AIdChanging(int value);
    partial void Oni_Address_AIdChanged();
    partial void Onnvc_Address_StreetAddressChanging(string value);
    partial void Onnvc_Address_StreetAddressChanged();
    partial void Onnvc_Address_ZipCodeChanging(string value);
    partial void Onnvc_Address_ZipCodeChanged();
    partial void Onnvc_Address_MobilePhoneChanging(string value);
    partial void Onnvc_Address_MobilePhoneChanged();
    partial void Onnvc_Address_TelPhoneChanging(string value);
    partial void Onnvc_Address_TelPhoneChanged();
    partial void Onnvc_Address_EmailChanging(string value);
    partial void Onnvc_Address_EmailChanged();
    partial void Oni_IntegralMobileIdChanging(int value);
    partial void Oni_IntegralMobileIdChanged();
    #endregion
		
		public t_IntegralOrder()
		{
			this._t_IntegralOrderDetails = new EntitySet<t_IntegralOrderDetails>(new Action<t_IntegralOrderDetails>(this.attach_t_IntegralOrderDetails), new Action<t_IntegralOrderDetails>(this.detach_t_IntegralOrderDetails));
			this._t_IntegralOrderOperateNote = new EntitySet<t_IntegralOrderOperateNote>(new Action<t_IntegralOrderOperateNote>(this.attach_t_IntegralOrderOperateNote), new Action<t_IntegralOrderOperateNote>(this.detach_t_IntegralOrderOperateNote));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_OrderNumber", DbType="NVarChar(50)")]
		public string nvc_OrderNumber
		{
			get
			{
				return this._nvc_OrderNumber;
			}
			set
			{
				if ((this._nvc_OrderNumber != value))
				{
					this.Onnvc_OrderNumberChanging(value);
					this.SendPropertyChanging();
					this._nvc_OrderNumber = value;
					this.SendPropertyChanged("nvc_OrderNumber");
					this.Onnvc_OrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberId", DbType="Int NOT NULL")]
		public int i_MemberId
		{
			get
			{
				return this._i_MemberId;
			}
			set
			{
				if ((this._i_MemberId != value))
				{
					this.Oni_MemberIdChanging(value);
					this.SendPropertyChanging();
					this._i_MemberId = value;
					this.SendPropertyChanged("i_MemberId");
					this.Oni_MemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_State", DbType="Int NOT NULL")]
		public int i_State
		{
			get
			{
				return this._i_State;
			}
			set
			{
				if ((this._i_State != value))
				{
					this.Oni_StateChanging(value);
					this.SendPropertyChanging();
					this._i_State = value;
					this.SendPropertyChanged("i_State");
					this.Oni_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_SumIntegral", DbType="Int NOT NULL")]
		public int i_SumIntegral
		{
			get
			{
				return this._i_SumIntegral;
			}
			set
			{
				if ((this._i_SumIntegral != value))
				{
					this.Oni_SumIntegralChanging(value);
					this.SendPropertyChanging();
					this._i_SumIntegral = value;
					this.SendPropertyChanged("i_SumIntegral");
					this.Oni_SumIntegralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_PSWay", DbType="NVarChar(50)")]
		public string nvc_PSWay
		{
			get
			{
				return this._nvc_PSWay;
			}
			set
			{
				if ((this._nvc_PSWay != value))
				{
					this.Onnvc_PSWayChanging(value);
					this.SendPropertyChanging();
					this._nvc_PSWay = value;
					this.SendPropertyChanged("nvc_PSWay");
					this.Onnvc_PSWayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralProductId", DbType="Int NOT NULL")]
		public int i_IntegralProductId
		{
			get
			{
				return this._i_IntegralProductId;
			}
			set
			{
				if ((this._i_IntegralProductId != value))
				{
					this.Oni_IntegralProductIdChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralProductId = value;
					this.SendPropertyChanged("i_IntegralProductId");
					this.Oni_IntegralProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_BuyNumber", DbType="Int NOT NULL")]
		public int i_BuyNumber
		{
			get
			{
				return this._i_BuyNumber;
			}
			set
			{
				if ((this._i_BuyNumber != value))
				{
					this.Oni_BuyNumberChanging(value);
					this.SendPropertyChanging();
					this._i_BuyNumber = value;
					this.SendPropertyChanged("i_BuyNumber");
					this.Oni_BuyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_AddressId", DbType="Int NOT NULL")]
		public int i_AddressId
		{
			get
			{
				return this._i_AddressId;
			}
			set
			{
				if ((this._i_AddressId != value))
				{
					this.Oni_AddressIdChanging(value);
					this.SendPropertyChanging();
					this._i_AddressId = value;
					this.SendPropertyChanged("i_AddressId");
					this.Oni_AddressIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_Consignee", DbType="NVarChar(50)")]
		public string nvc_Address_Consignee
		{
			get
			{
				return this._nvc_Address_Consignee;
			}
			set
			{
				if ((this._nvc_Address_Consignee != value))
				{
					this.Onnvc_Address_ConsigneeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_Consignee = value;
					this.SendPropertyChanged("nvc_Address_Consignee");
					this.Onnvc_Address_ConsigneeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Address_GId", DbType="Int NOT NULL")]
		public int i_Address_GId
		{
			get
			{
				return this._i_Address_GId;
			}
			set
			{
				if ((this._i_Address_GId != value))
				{
					this.Oni_Address_GIdChanging(value);
					this.SendPropertyChanging();
					this._i_Address_GId = value;
					this.SendPropertyChanged("i_Address_GId");
					this.Oni_Address_GIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Address_PId", DbType="Int NOT NULL")]
		public int i_Address_PId
		{
			get
			{
				return this._i_Address_PId;
			}
			set
			{
				if ((this._i_Address_PId != value))
				{
					this.Oni_Address_PIdChanging(value);
					this.SendPropertyChanging();
					this._i_Address_PId = value;
					this.SendPropertyChanged("i_Address_PId");
					this.Oni_Address_PIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Address_CId", DbType="Int NOT NULL")]
		public int i_Address_CId
		{
			get
			{
				return this._i_Address_CId;
			}
			set
			{
				if ((this._i_Address_CId != value))
				{
					this.Oni_Address_CIdChanging(value);
					this.SendPropertyChanging();
					this._i_Address_CId = value;
					this.SendPropertyChanged("i_Address_CId");
					this.Oni_Address_CIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Address_AId", DbType="Int NOT NULL")]
		public int i_Address_AId
		{
			get
			{
				return this._i_Address_AId;
			}
			set
			{
				if ((this._i_Address_AId != value))
				{
					this.Oni_Address_AIdChanging(value);
					this.SendPropertyChanging();
					this._i_Address_AId = value;
					this.SendPropertyChanged("i_Address_AId");
					this.Oni_Address_AIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_StreetAddress", DbType="NVarChar(500)")]
		public string nvc_Address_StreetAddress
		{
			get
			{
				return this._nvc_Address_StreetAddress;
			}
			set
			{
				if ((this._nvc_Address_StreetAddress != value))
				{
					this.Onnvc_Address_StreetAddressChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_StreetAddress = value;
					this.SendPropertyChanged("nvc_Address_StreetAddress");
					this.Onnvc_Address_StreetAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_ZipCode", DbType="VarChar(6)")]
		public string nvc_Address_ZipCode
		{
			get
			{
				return this._nvc_Address_ZipCode;
			}
			set
			{
				if ((this._nvc_Address_ZipCode != value))
				{
					this.Onnvc_Address_ZipCodeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_ZipCode = value;
					this.SendPropertyChanged("nvc_Address_ZipCode");
					this.Onnvc_Address_ZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_MobilePhone", DbType="VarChar(50)")]
		public string nvc_Address_MobilePhone
		{
			get
			{
				return this._nvc_Address_MobilePhone;
			}
			set
			{
				if ((this._nvc_Address_MobilePhone != value))
				{
					this.Onnvc_Address_MobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_MobilePhone = value;
					this.SendPropertyChanged("nvc_Address_MobilePhone");
					this.Onnvc_Address_MobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_TelPhone", DbType="VarChar(50)")]
		public string nvc_Address_TelPhone
		{
			get
			{
				return this._nvc_Address_TelPhone;
			}
			set
			{
				if ((this._nvc_Address_TelPhone != value))
				{
					this.Onnvc_Address_TelPhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_TelPhone = value;
					this.SendPropertyChanged("nvc_Address_TelPhone");
					this.Onnvc_Address_TelPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address_Email", DbType="VarChar(50)")]
		public string nvc_Address_Email
		{
			get
			{
				return this._nvc_Address_Email;
			}
			set
			{
				if ((this._nvc_Address_Email != value))
				{
					this.Onnvc_Address_EmailChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address_Email = value;
					this.SendPropertyChanged("nvc_Address_Email");
					this.Onnvc_Address_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralMobileId", DbType="Int NOT NULL")]
		public int i_IntegralMobileId
		{
			get
			{
				return this._i_IntegralMobileId;
			}
			set
			{
				if ((this._i_IntegralMobileId != value))
				{
					this.Oni_IntegralMobileIdChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralMobileId = value;
					this.SendPropertyChanged("i_IntegralMobileId");
					this.Oni_IntegralMobileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_IntegralOrder_t_IntegralOrderDetails", Storage="_t_IntegralOrderDetails", ThisKey="i_Id", OtherKey="i_IntegralOrderId")]
		public EntitySet<t_IntegralOrderDetails> t_IntegralOrderDetails
		{
			get
			{
				return this._t_IntegralOrderDetails;
			}
			set
			{
				this._t_IntegralOrderDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_IntegralOrder_t_IntegralOrderOperateNote", Storage="_t_IntegralOrderOperateNote", ThisKey="i_Id", OtherKey="i_OrderId")]
		public EntitySet<t_IntegralOrderOperateNote> t_IntegralOrderOperateNote
		{
			get
			{
				return this._t_IntegralOrderOperateNote;
			}
			set
			{
				this._t_IntegralOrderOperateNote.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_t_IntegralOrderDetails(t_IntegralOrderDetails entity)
		{
			this.SendPropertyChanging();
			entity.t_IntegralOrder = this;
		}
		
		private void detach_t_IntegralOrderDetails(t_IntegralOrderDetails entity)
		{
			this.SendPropertyChanging();
			entity.t_IntegralOrder = null;
		}
		
		private void attach_t_IntegralOrderOperateNote(t_IntegralOrderOperateNote entity)
		{
			this.SendPropertyChanging();
			entity.t_IntegralOrder = this;
		}
		
		private void detach_t_IntegralOrderOperateNote(t_IntegralOrderOperateNote entity)
		{
			this.SendPropertyChanging();
			entity.t_IntegralOrder = null;
		}
	}
}
#pragma warning restore 1591
