#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.33440
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zscq.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_zscq")]
	public partial class DataProcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataProcDataContext() : 
				base(global::zscq.Model.Properties.Settings.Default.db_zscqConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataProcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_Count_Case_AdminStatus")]
		public ISingleResult<pro_Count_Case_AdminStatusResult> pro_Count_Case_AdminStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> caseType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), caseType, userid);
			return ((ISingleResult<pro_Count_Case_AdminStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_Count_OrderStatus")]
		public ISingleResult<pro_Count_OrderStatusResult> pro_Count_OrderStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> caseType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), caseType, userid);
			return ((ISingleResult<pro_Count_OrderStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_Count_TrademarkType")]
		public ISingleResult<pro_Count_TrademarkTypeResult> pro_Count_TrademarkType([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
			return ((ISingleResult<pro_Count_TrademarkTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_Count_ApplyUser")]
		public ISingleResult<pro_Count_ApplyUserResult> pro_Count_ApplyUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
			return ((ISingleResult<pro_Count_ApplyUserResult>)(result.ReturnValue));
		}
	}
	
	public partial class pro_Count_Case_AdminStatusResult
	{
		
		private string _StatusName;
		
		private System.Nullable<int> _StatusValue;
		
		private string _tids;
		
		private System.Nullable<int> _counts;
		
		public pro_Count_Case_AdminStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusName", DbType="VarChar(50)")]
		public string StatusName
		{
			get
			{
				return this._StatusName;
			}
			set
			{
				if ((this._StatusName != value))
				{
					this._StatusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusValue", DbType="Int")]
		public System.Nullable<int> StatusValue
		{
			get
			{
				return this._StatusValue;
			}
			set
			{
				if ((this._StatusValue != value))
				{
					this._StatusValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tids", DbType="NVarChar(MAX)")]
		public string tids
		{
			get
			{
				return this._tids;
			}
			set
			{
				if ((this._tids != value))
				{
					this._tids = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counts", DbType="Int")]
		public System.Nullable<int> counts
		{
			get
			{
				return this._counts;
			}
			set
			{
				if ((this._counts != value))
				{
					this._counts = value;
				}
			}
		}
	}
	
	public partial class pro_Count_OrderStatusResult
	{
		
		private string _StatusName;
		
		private System.Nullable<int> _StatusValue;
		
		private string _tids;
		
		private System.Nullable<int> _counts;
		
		public pro_Count_OrderStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusName", DbType="VarChar(50)")]
		public string StatusName
		{
			get
			{
				return this._StatusName;
			}
			set
			{
				if ((this._StatusName != value))
				{
					this._StatusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusValue", DbType="Int")]
		public System.Nullable<int> StatusValue
		{
			get
			{
				return this._StatusValue;
			}
			set
			{
				if ((this._StatusValue != value))
				{
					this._StatusValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tids", DbType="NVarChar(MAX)")]
		public string tids
		{
			get
			{
				return this._tids;
			}
			set
			{
				if ((this._tids != value))
				{
					this._tids = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counts", DbType="Int")]
		public System.Nullable<int> counts
		{
			get
			{
				return this._counts;
			}
			set
			{
				if ((this._counts != value))
				{
					this._counts = value;
				}
			}
		}
	}
	
	public partial class pro_Count_TrademarkTypeResult
	{
		
		private string _CategoryCode;
		
		private string _tidsApply;
		
		private System.Nullable<int> _countsApply;
		
		private string _tidsRenewal;
		
		private System.Nullable<int> _countsRenewal;
		
		public pro_Count_TrademarkTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryCode", DbType="NVarChar(50)")]
		public string CategoryCode
		{
			get
			{
				return this._CategoryCode;
			}
			set
			{
				if ((this._CategoryCode != value))
				{
					this._CategoryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tidsApply", DbType="NVarChar(MAX)")]
		public string tidsApply
		{
			get
			{
				return this._tidsApply;
			}
			set
			{
				if ((this._tidsApply != value))
				{
					this._tidsApply = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countsApply", DbType="Int")]
		public System.Nullable<int> countsApply
		{
			get
			{
				return this._countsApply;
			}
			set
			{
				if ((this._countsApply != value))
				{
					this._countsApply = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tidsRenewal", DbType="NVarChar(MAX)")]
		public string tidsRenewal
		{
			get
			{
				return this._tidsRenewal;
			}
			set
			{
				if ((this._tidsRenewal != value))
				{
					this._tidsRenewal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countsRenewal", DbType="Int")]
		public System.Nullable<int> countsRenewal
		{
			get
			{
				return this._countsRenewal;
			}
			set
			{
				if ((this._countsRenewal != value))
				{
					this._countsRenewal = value;
				}
			}
		}
	}
	
	public partial class pro_Count_ApplyUserResult
	{
		
		private string _ApplyName;
		
		private string _tidsApply;
		
		private System.Nullable<int> _countsApply;
		
		private string _tidsRenewal;
		
		private System.Nullable<int> _countsRenewal;
		
		public pro_Count_ApplyUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplyName
		{
			get
			{
				return this._ApplyName;
			}
			set
			{
				if ((this._ApplyName != value))
				{
					this._ApplyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tidsApply", DbType="NVarChar(MAX)")]
		public string tidsApply
		{
			get
			{
				return this._tidsApply;
			}
			set
			{
				if ((this._tidsApply != value))
				{
					this._tidsApply = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countsApply", DbType="Int")]
		public System.Nullable<int> countsApply
		{
			get
			{
				return this._countsApply;
			}
			set
			{
				if ((this._countsApply != value))
				{
					this._countsApply = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tidsRenewal", DbType="NVarChar(MAX)")]
		public string tidsRenewal
		{
			get
			{
				return this._tidsRenewal;
			}
			set
			{
				if ((this._tidsRenewal != value))
				{
					this._tidsRenewal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countsRenewal", DbType="Int")]
		public System.Nullable<int> countsRenewal
		{
			get
			{
				return this._countsRenewal;
			}
			set
			{
				if ((this._countsRenewal != value))
				{
					this._countsRenewal = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
