#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zscq.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_zscq")]
	public partial class DataMemberDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_Collection(t_Collection instance);
    partial void Updatet_Collection(t_Collection instance);
    partial void Deletet_Collection(t_Collection instance);
    partial void Insertt_ReceiveAddress(t_ReceiveAddress instance);
    partial void Updatet_ReceiveAddress(t_ReceiveAddress instance);
    partial void Deletet_ReceiveAddress(t_ReceiveAddress instance);
    partial void Insertt_UserIntegralNote(t_UserIntegralNote instance);
    partial void Updatet_UserIntegralNote(t_UserIntegralNote instance);
    partial void Deletet_UserIntegralNote(t_UserIntegralNote instance);
    partial void Insertt_CouponType(t_CouponType instance);
    partial void Updatet_CouponType(t_CouponType instance);
    partial void Deletet_CouponType(t_CouponType instance);
    partial void Insertt_Member(t_Member instance);
    partial void Updatet_Member(t_Member instance);
    partial void Deletet_Member(t_Member instance);
    partial void Insertt_MemberGrade(t_MemberGrade instance);
    partial void Updatet_MemberGrade(t_MemberGrade instance);
    partial void Deletet_MemberGrade(t_MemberGrade instance);
    partial void Insertt_Coupon(t_Coupon instance);
    partial void Updatet_Coupon(t_Coupon instance);
    partial void Deletet_Coupon(t_Coupon instance);
    partial void Insertt_OnlineMessage(t_OnlineMessage instance);
    partial void Updatet_OnlineMessage(t_OnlineMessage instance);
    partial void Deletet_OnlineMessage(t_OnlineMessage instance);
    #endregion
		
		public DataMemberDataContext() : 
				base(global::zscq.Model.Properties.Settings.Default.db_zscqConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataMemberDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMemberDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMemberDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMemberDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_Collection> t_Collection
		{
			get
			{
				return this.GetTable<t_Collection>();
			}
		}
		
		public System.Data.Linq.Table<t_ReceiveAddress> t_ReceiveAddress
		{
			get
			{
				return this.GetTable<t_ReceiveAddress>();
			}
		}
		
		public System.Data.Linq.Table<t_UserIntegralNote> t_UserIntegralNote
		{
			get
			{
				return this.GetTable<t_UserIntegralNote>();
			}
		}
		
		public System.Data.Linq.Table<t_CouponType> t_CouponType
		{
			get
			{
				return this.GetTable<t_CouponType>();
			}
		}
		
		public System.Data.Linq.Table<t_Member> t_Member
		{
			get
			{
				return this.GetTable<t_Member>();
			}
		}
		
		public System.Data.Linq.Table<t_MemberGrade> t_MemberGrade
		{
			get
			{
				return this.GetTable<t_MemberGrade>();
			}
		}
		
		public System.Data.Linq.Table<t_Coupon> t_Coupon
		{
			get
			{
				return this.GetTable<t_Coupon>();
			}
		}
		
		public System.Data.Linq.Table<t_OnlineMessage> t_OnlineMessage
		{
			get
			{
				return this.GetTable<t_OnlineMessage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Collection")]
	public partial class t_Collection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private int _i_MemberId;
		
		private int _i_ProductId;
		
		private System.DateTime _dt_AddTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Oni_MemberIdChanging(int value);
    partial void Oni_MemberIdChanged();
    partial void Oni_ProductIdChanging(int value);
    partial void Oni_ProductIdChanged();
    partial void Ondt_AddTimeChanging(System.DateTime value);
    partial void Ondt_AddTimeChanged();
    #endregion
		
		public t_Collection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberId", DbType="Int NOT NULL")]
		public int i_MemberId
		{
			get
			{
				return this._i_MemberId;
			}
			set
			{
				if ((this._i_MemberId != value))
				{
					this.Oni_MemberIdChanging(value);
					this.SendPropertyChanging();
					this._i_MemberId = value;
					this.SendPropertyChanged("i_MemberId");
					this.Oni_MemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ProductId", DbType="Int NOT NULL")]
		public int i_ProductId
		{
			get
			{
				return this._i_ProductId;
			}
			set
			{
				if ((this._i_ProductId != value))
				{
					this.Oni_ProductIdChanging(value);
					this.SendPropertyChanging();
					this._i_ProductId = value;
					this.SendPropertyChanged("i_ProductId");
					this.Oni_ProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_ReceiveAddress")]
	public partial class t_ReceiveAddress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private string _nvc_Consignee;
		
		private int _i_Gid;
		
		private int _i_PId;
		
		private int _i_CId;
		
		private int _i_AId;
		
		private string _nvc_StreetAddress;
		
		private string _nvc_ZipCode;
		
		private string _nvc_MobilePhone;
		
		private string _nvc_TelPhone;
		
		private string _nvc_Email;
		
		private int _i_MemberId;
		
		private EntityRef<t_Member> _t_Member;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Onnvc_ConsigneeChanging(string value);
    partial void Onnvc_ConsigneeChanged();
    partial void Oni_GidChanging(int value);
    partial void Oni_GidChanged();
    partial void Oni_PIdChanging(int value);
    partial void Oni_PIdChanged();
    partial void Oni_CIdChanging(int value);
    partial void Oni_CIdChanged();
    partial void Oni_AIdChanging(int value);
    partial void Oni_AIdChanged();
    partial void Onnvc_StreetAddressChanging(string value);
    partial void Onnvc_StreetAddressChanged();
    partial void Onnvc_ZipCodeChanging(string value);
    partial void Onnvc_ZipCodeChanged();
    partial void Onnvc_MobilePhoneChanging(string value);
    partial void Onnvc_MobilePhoneChanged();
    partial void Onnvc_TelPhoneChanging(string value);
    partial void Onnvc_TelPhoneChanged();
    partial void Onnvc_EmailChanging(string value);
    partial void Onnvc_EmailChanged();
    partial void Oni_MemberIdChanging(int value);
    partial void Oni_MemberIdChanged();
    #endregion
		
		public t_ReceiveAddress()
		{
			this._t_Member = default(EntityRef<t_Member>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Consignee", DbType="NVarChar(50)")]
		public string nvc_Consignee
		{
			get
			{
				return this._nvc_Consignee;
			}
			set
			{
				if ((this._nvc_Consignee != value))
				{
					this.Onnvc_ConsigneeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Consignee = value;
					this.SendPropertyChanged("nvc_Consignee");
					this.Onnvc_ConsigneeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Gid", DbType="Int NOT NULL")]
		public int i_Gid
		{
			get
			{
				return this._i_Gid;
			}
			set
			{
				if ((this._i_Gid != value))
				{
					this.Oni_GidChanging(value);
					this.SendPropertyChanging();
					this._i_Gid = value;
					this.SendPropertyChanged("i_Gid");
					this.Oni_GidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_PId", DbType="Int NOT NULL")]
		public int i_PId
		{
			get
			{
				return this._i_PId;
			}
			set
			{
				if ((this._i_PId != value))
				{
					this.Oni_PIdChanging(value);
					this.SendPropertyChanging();
					this._i_PId = value;
					this.SendPropertyChanged("i_PId");
					this.Oni_PIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_CId", DbType="Int NOT NULL")]
		public int i_CId
		{
			get
			{
				return this._i_CId;
			}
			set
			{
				if ((this._i_CId != value))
				{
					this.Oni_CIdChanging(value);
					this.SendPropertyChanging();
					this._i_CId = value;
					this.SendPropertyChanged("i_CId");
					this.Oni_CIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_AId", DbType="Int NOT NULL")]
		public int i_AId
		{
			get
			{
				return this._i_AId;
			}
			set
			{
				if ((this._i_AId != value))
				{
					this.Oni_AIdChanging(value);
					this.SendPropertyChanging();
					this._i_AId = value;
					this.SendPropertyChanged("i_AId");
					this.Oni_AIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_StreetAddress", DbType="NVarChar(500)")]
		public string nvc_StreetAddress
		{
			get
			{
				return this._nvc_StreetAddress;
			}
			set
			{
				if ((this._nvc_StreetAddress != value))
				{
					this.Onnvc_StreetAddressChanging(value);
					this.SendPropertyChanging();
					this._nvc_StreetAddress = value;
					this.SendPropertyChanged("nvc_StreetAddress");
					this.Onnvc_StreetAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_ZipCode", DbType="VarChar(6)")]
		public string nvc_ZipCode
		{
			get
			{
				return this._nvc_ZipCode;
			}
			set
			{
				if ((this._nvc_ZipCode != value))
				{
					this.Onnvc_ZipCodeChanging(value);
					this.SendPropertyChanging();
					this._nvc_ZipCode = value;
					this.SendPropertyChanged("nvc_ZipCode");
					this.Onnvc_ZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_MobilePhone", DbType="VarChar(50)")]
		public string nvc_MobilePhone
		{
			get
			{
				return this._nvc_MobilePhone;
			}
			set
			{
				if ((this._nvc_MobilePhone != value))
				{
					this.Onnvc_MobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_MobilePhone = value;
					this.SendPropertyChanged("nvc_MobilePhone");
					this.Onnvc_MobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_TelPhone", DbType="VarChar(50)")]
		public string nvc_TelPhone
		{
			get
			{
				return this._nvc_TelPhone;
			}
			set
			{
				if ((this._nvc_TelPhone != value))
				{
					this.Onnvc_TelPhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_TelPhone = value;
					this.SendPropertyChanged("nvc_TelPhone");
					this.Onnvc_TelPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Email", DbType="VarChar(50)")]
		public string nvc_Email
		{
			get
			{
				return this._nvc_Email;
			}
			set
			{
				if ((this._nvc_Email != value))
				{
					this.Onnvc_EmailChanging(value);
					this.SendPropertyChanging();
					this._nvc_Email = value;
					this.SendPropertyChanged("nvc_Email");
					this.Onnvc_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberId", DbType="Int NOT NULL")]
		public int i_MemberId
		{
			get
			{
				return this._i_MemberId;
			}
			set
			{
				if ((this._i_MemberId != value))
				{
					if (this._t_Member.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oni_MemberIdChanging(value);
					this.SendPropertyChanging();
					this._i_MemberId = value;
					this.SendPropertyChanged("i_MemberId");
					this.Oni_MemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Member_t_ReceiveAddress", Storage="_t_Member", ThisKey="i_MemberId", OtherKey="i_Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public t_Member t_Member
		{
			get
			{
				return this._t_Member.Entity;
			}
			set
			{
				t_Member previousValue = this._t_Member.Entity;
				if (((previousValue != value) 
							|| (this._t_Member.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Member.Entity = null;
						previousValue.t_ReceiveAddress.Remove(this);
					}
					this._t_Member.Entity = value;
					if ((value != null))
					{
						value.t_ReceiveAddress.Add(this);
						this._i_MemberId = value.i_Id;
					}
					else
					{
						this._i_MemberId = default(int);
					}
					this.SendPropertyChanged("t_Member");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_UserIntegralNote")]
	public partial class t_UserIntegralNote : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private int _i_UserId;
		
		private int _i_Integral_1;
		
		private int _i_Integral_2;
		
		private int _i_Integral_3;
		
		private string _nvc_NoteType;
		
		private System.DateTime _dt_AddTime;
		
		private System.Nullable<int> _i_status;
		
		private System.Nullable<int> _i_OrderID;
		
		private int _i_IntegralMobileId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Oni_UserIdChanging(int value);
    partial void Oni_UserIdChanged();
    partial void Oni_Integral_1Changing(int value);
    partial void Oni_Integral_1Changed();
    partial void Oni_Integral_2Changing(int value);
    partial void Oni_Integral_2Changed();
    partial void Oni_Integral_3Changing(int value);
    partial void Oni_Integral_3Changed();
    partial void Onnvc_NoteTypeChanging(string value);
    partial void Onnvc_NoteTypeChanged();
    partial void Ondt_AddTimeChanging(System.DateTime value);
    partial void Ondt_AddTimeChanged();
    partial void Oni_statusChanging(System.Nullable<int> value);
    partial void Oni_statusChanged();
    partial void Oni_OrderIDChanging(System.Nullable<int> value);
    partial void Oni_OrderIDChanged();
    partial void Oni_IntegralMobileIdChanging(int value);
    partial void Oni_IntegralMobileIdChanged();
    #endregion
		
		public t_UserIntegralNote()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_UserId", DbType="Int NOT NULL")]
		public int i_UserId
		{
			get
			{
				return this._i_UserId;
			}
			set
			{
				if ((this._i_UserId != value))
				{
					this.Oni_UserIdChanging(value);
					this.SendPropertyChanging();
					this._i_UserId = value;
					this.SendPropertyChanged("i_UserId");
					this.Oni_UserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Integral_1", DbType="Int NOT NULL")]
		public int i_Integral_1
		{
			get
			{
				return this._i_Integral_1;
			}
			set
			{
				if ((this._i_Integral_1 != value))
				{
					this.Oni_Integral_1Changing(value);
					this.SendPropertyChanging();
					this._i_Integral_1 = value;
					this.SendPropertyChanged("i_Integral_1");
					this.Oni_Integral_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Integral_2", DbType="Int NOT NULL")]
		public int i_Integral_2
		{
			get
			{
				return this._i_Integral_2;
			}
			set
			{
				if ((this._i_Integral_2 != value))
				{
					this.Oni_Integral_2Changing(value);
					this.SendPropertyChanging();
					this._i_Integral_2 = value;
					this.SendPropertyChanged("i_Integral_2");
					this.Oni_Integral_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Integral_3", DbType="Int NOT NULL")]
		public int i_Integral_3
		{
			get
			{
				return this._i_Integral_3;
			}
			set
			{
				if ((this._i_Integral_3 != value))
				{
					this.Oni_Integral_3Changing(value);
					this.SendPropertyChanging();
					this._i_Integral_3 = value;
					this.SendPropertyChanged("i_Integral_3");
					this.Oni_Integral_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_NoteType", DbType="NVarChar(50)")]
		public string nvc_NoteType
		{
			get
			{
				return this._nvc_NoteType;
			}
			set
			{
				if ((this._nvc_NoteType != value))
				{
					this.Onnvc_NoteTypeChanging(value);
					this.SendPropertyChanging();
					this._nvc_NoteType = value;
					this.SendPropertyChanged("nvc_NoteType");
					this.Onnvc_NoteTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime NOT NULL")]
		public System.DateTime dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_status", DbType="Int")]
		public System.Nullable<int> i_status
		{
			get
			{
				return this._i_status;
			}
			set
			{
				if ((this._i_status != value))
				{
					this.Oni_statusChanging(value);
					this.SendPropertyChanging();
					this._i_status = value;
					this.SendPropertyChanged("i_status");
					this.Oni_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_OrderID", DbType="Int")]
		public System.Nullable<int> i_OrderID
		{
			get
			{
				return this._i_OrderID;
			}
			set
			{
				if ((this._i_OrderID != value))
				{
					this.Oni_OrderIDChanging(value);
					this.SendPropertyChanging();
					this._i_OrderID = value;
					this.SendPropertyChanged("i_OrderID");
					this.Oni_OrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralMobileId", DbType="Int NOT NULL")]
		public int i_IntegralMobileId
		{
			get
			{
				return this._i_IntegralMobileId;
			}
			set
			{
				if ((this._i_IntegralMobileId != value))
				{
					this.Oni_IntegralMobileIdChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralMobileId = value;
					this.SendPropertyChanged("i_IntegralMobileId");
					this.Oni_IntegralMobileIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_CouponType")]
	public partial class t_CouponType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private string _nvc_Name;
		
		private string _nvc_ENName;
		
		private string _nvc_JPName;
		
		private string _nvc_KRName;
		
		private int _i_Type;
		
		private int _i_SId;
		
		private int _i_Where;
		
		private int _i_Money;
		
		private int _i_NeedJifen;
		
		private int _i_RegGiveNumber;
		
		private int _i_Where1;
		
		private int _i_Money1;
		
		private int _i_Where2;
		
		private int _i_Money2;
		
		private int _i_Where3;
		
		private int _i_Money3;
		
		private int _i_Where4;
		
		private int _i_Money4;
		
		private int _i_GuojiType;
		
		private int _i_TimeLength;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Onnvc_NameChanging(string value);
    partial void Onnvc_NameChanged();
    partial void Onnvc_ENNameChanging(string value);
    partial void Onnvc_ENNameChanged();
    partial void Onnvc_JPNameChanging(string value);
    partial void Onnvc_JPNameChanged();
    partial void Onnvc_KRNameChanging(string value);
    partial void Onnvc_KRNameChanged();
    partial void Oni_TypeChanging(int value);
    partial void Oni_TypeChanged();
    partial void Oni_SIdChanging(int value);
    partial void Oni_SIdChanged();
    partial void Oni_WhereChanging(int value);
    partial void Oni_WhereChanged();
    partial void Oni_MoneyChanging(int value);
    partial void Oni_MoneyChanged();
    partial void Oni_NeedJifenChanging(int value);
    partial void Oni_NeedJifenChanged();
    partial void Oni_RegGiveNumberChanging(int value);
    partial void Oni_RegGiveNumberChanged();
    partial void Oni_Where1Changing(int value);
    partial void Oni_Where1Changed();
    partial void Oni_Money1Changing(int value);
    partial void Oni_Money1Changed();
    partial void Oni_Where2Changing(int value);
    partial void Oni_Where2Changed();
    partial void Oni_Money2Changing(int value);
    partial void Oni_Money2Changed();
    partial void Oni_Where3Changing(int value);
    partial void Oni_Where3Changed();
    partial void Oni_Money3Changing(int value);
    partial void Oni_Money3Changed();
    partial void Oni_Where4Changing(int value);
    partial void Oni_Where4Changed();
    partial void Oni_Money4Changing(int value);
    partial void Oni_Money4Changed();
    partial void Oni_GuojiTypeChanging(int value);
    partial void Oni_GuojiTypeChanged();
    partial void Oni_TimeLengthChanging(int value);
    partial void Oni_TimeLengthChanged();
    #endregion
		
		public t_CouponType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Name", DbType="NVarChar(50)")]
		public string nvc_Name
		{
			get
			{
				return this._nvc_Name;
			}
			set
			{
				if ((this._nvc_Name != value))
				{
					this.Onnvc_NameChanging(value);
					this.SendPropertyChanging();
					this._nvc_Name = value;
					this.SendPropertyChanged("nvc_Name");
					this.Onnvc_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_ENName", DbType="NVarChar(50)")]
		public string nvc_ENName
		{
			get
			{
				return this._nvc_ENName;
			}
			set
			{
				if ((this._nvc_ENName != value))
				{
					this.Onnvc_ENNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_ENName = value;
					this.SendPropertyChanged("nvc_ENName");
					this.Onnvc_ENNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_JPName", DbType="NVarChar(50)")]
		public string nvc_JPName
		{
			get
			{
				return this._nvc_JPName;
			}
			set
			{
				if ((this._nvc_JPName != value))
				{
					this.Onnvc_JPNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_JPName = value;
					this.SendPropertyChanged("nvc_JPName");
					this.Onnvc_JPNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_KRName", DbType="NVarChar(50)")]
		public string nvc_KRName
		{
			get
			{
				return this._nvc_KRName;
			}
			set
			{
				if ((this._nvc_KRName != value))
				{
					this.Onnvc_KRNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_KRName = value;
					this.SendPropertyChanged("nvc_KRName");
					this.Onnvc_KRNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Type", DbType="Int NOT NULL")]
		public int i_Type
		{
			get
			{
				return this._i_Type;
			}
			set
			{
				if ((this._i_Type != value))
				{
					this.Oni_TypeChanging(value);
					this.SendPropertyChanging();
					this._i_Type = value;
					this.SendPropertyChanged("i_Type");
					this.Oni_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_SId", DbType="Int NOT NULL")]
		public int i_SId
		{
			get
			{
				return this._i_SId;
			}
			set
			{
				if ((this._i_SId != value))
				{
					this.Oni_SIdChanging(value);
					this.SendPropertyChanging();
					this._i_SId = value;
					this.SendPropertyChanged("i_SId");
					this.Oni_SIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Where", DbType="Int NOT NULL")]
		public int i_Where
		{
			get
			{
				return this._i_Where;
			}
			set
			{
				if ((this._i_Where != value))
				{
					this.Oni_WhereChanging(value);
					this.SendPropertyChanging();
					this._i_Where = value;
					this.SendPropertyChanged("i_Where");
					this.Oni_WhereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Money", DbType="Int NOT NULL")]
		public int i_Money
		{
			get
			{
				return this._i_Money;
			}
			set
			{
				if ((this._i_Money != value))
				{
					this.Oni_MoneyChanging(value);
					this.SendPropertyChanging();
					this._i_Money = value;
					this.SendPropertyChanged("i_Money");
					this.Oni_MoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_NeedJifen", DbType="Int NOT NULL")]
		public int i_NeedJifen
		{
			get
			{
				return this._i_NeedJifen;
			}
			set
			{
				if ((this._i_NeedJifen != value))
				{
					this.Oni_NeedJifenChanging(value);
					this.SendPropertyChanging();
					this._i_NeedJifen = value;
					this.SendPropertyChanged("i_NeedJifen");
					this.Oni_NeedJifenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_RegGiveNumber", DbType="Int NOT NULL")]
		public int i_RegGiveNumber
		{
			get
			{
				return this._i_RegGiveNumber;
			}
			set
			{
				if ((this._i_RegGiveNumber != value))
				{
					this.Oni_RegGiveNumberChanging(value);
					this.SendPropertyChanging();
					this._i_RegGiveNumber = value;
					this.SendPropertyChanged("i_RegGiveNumber");
					this.Oni_RegGiveNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Where1", DbType="Int NOT NULL")]
		public int i_Where1
		{
			get
			{
				return this._i_Where1;
			}
			set
			{
				if ((this._i_Where1 != value))
				{
					this.Oni_Where1Changing(value);
					this.SendPropertyChanging();
					this._i_Where1 = value;
					this.SendPropertyChanged("i_Where1");
					this.Oni_Where1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Money1", DbType="Int NOT NULL")]
		public int i_Money1
		{
			get
			{
				return this._i_Money1;
			}
			set
			{
				if ((this._i_Money1 != value))
				{
					this.Oni_Money1Changing(value);
					this.SendPropertyChanging();
					this._i_Money1 = value;
					this.SendPropertyChanged("i_Money1");
					this.Oni_Money1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Where2", DbType="Int NOT NULL")]
		public int i_Where2
		{
			get
			{
				return this._i_Where2;
			}
			set
			{
				if ((this._i_Where2 != value))
				{
					this.Oni_Where2Changing(value);
					this.SendPropertyChanging();
					this._i_Where2 = value;
					this.SendPropertyChanged("i_Where2");
					this.Oni_Where2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Money2", DbType="Int NOT NULL")]
		public int i_Money2
		{
			get
			{
				return this._i_Money2;
			}
			set
			{
				if ((this._i_Money2 != value))
				{
					this.Oni_Money2Changing(value);
					this.SendPropertyChanging();
					this._i_Money2 = value;
					this.SendPropertyChanged("i_Money2");
					this.Oni_Money2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Where3", DbType="Int NOT NULL")]
		public int i_Where3
		{
			get
			{
				return this._i_Where3;
			}
			set
			{
				if ((this._i_Where3 != value))
				{
					this.Oni_Where3Changing(value);
					this.SendPropertyChanging();
					this._i_Where3 = value;
					this.SendPropertyChanged("i_Where3");
					this.Oni_Where3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Money3", DbType="Int NOT NULL")]
		public int i_Money3
		{
			get
			{
				return this._i_Money3;
			}
			set
			{
				if ((this._i_Money3 != value))
				{
					this.Oni_Money3Changing(value);
					this.SendPropertyChanging();
					this._i_Money3 = value;
					this.SendPropertyChanged("i_Money3");
					this.Oni_Money3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Where4", DbType="Int NOT NULL")]
		public int i_Where4
		{
			get
			{
				return this._i_Where4;
			}
			set
			{
				if ((this._i_Where4 != value))
				{
					this.Oni_Where4Changing(value);
					this.SendPropertyChanging();
					this._i_Where4 = value;
					this.SendPropertyChanged("i_Where4");
					this.Oni_Where4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Money4", DbType="Int NOT NULL")]
		public int i_Money4
		{
			get
			{
				return this._i_Money4;
			}
			set
			{
				if ((this._i_Money4 != value))
				{
					this.Oni_Money4Changing(value);
					this.SendPropertyChanging();
					this._i_Money4 = value;
					this.SendPropertyChanged("i_Money4");
					this.Oni_Money4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_GuojiType", DbType="Int NOT NULL")]
		public int i_GuojiType
		{
			get
			{
				return this._i_GuojiType;
			}
			set
			{
				if ((this._i_GuojiType != value))
				{
					this.Oni_GuojiTypeChanging(value);
					this.SendPropertyChanging();
					this._i_GuojiType = value;
					this.SendPropertyChanged("i_GuojiType");
					this.Oni_GuojiTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_TimeLength", DbType="Int NOT NULL")]
		public int i_TimeLength
		{
			get
			{
				return this._i_TimeLength;
			}
			set
			{
				if ((this._i_TimeLength != value))
				{
					this.Oni_TimeLengthChanging(value);
					this.SendPropertyChanging();
					this._i_TimeLength = value;
					this.SendPropertyChanged("i_TimeLength");
					this.Oni_TimeLengthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Member")]
	public partial class t_Member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private string _nvc_UserNum;
		
		private string _nvc_Name;
		
		private string _nvc_EnName;
		
		private string _nvc_Company;
		
		private string _nvc_EnCompany;
		
		private string _nvc_DaiLiName;
		
		private string _nvc_RealName;
		
		private string _nvc_FaxNumber;
		
		private string _nvc_PassWord;
		
		private string _nvc_IDCard;
		
		private string _nvc_TitlePhoto;
		
		private System.Nullable<int> _i_CountryId;
		
		private System.Nullable<int> _i_UserTypeId;
		
		private System.Nullable<int> _i_RegTypeId;
		
		private int _i_Grade;
		
		private int _i_GuoJiId;
		
		private int _i_ProvinceId;
		
		private int _i_CityId;
		
		private int _i_AreaId;
		
		private string _nvc_Address;
		
		private string _nvc_EnAddress;
		
		private string _nvc_ZipCode;
		
		private string _nvc_MobilePhone;
		
		private string _nvc_TelPhone;
		
		private string _nvc_Email;
		
		private int _i_DefaultAddress;
		
		private int _i_Sex;
		
		private string _nvc_Age;
		
		private string _nvc_IP;
		
		private int _i_Integral;
		
		private int _i_Please;
		
		private System.Nullable<System.DateTime> _dt_AddTime;
		
		private System.Nullable<int> _is_alipay;
		
		private string _text_pass;
		
		private System.Nullable<decimal> _dm_Money;
		
		private string _nvc_Personalized;
		
		private int _i_MemberType;
		
		private string _nvc_EnglishName;
		
		private string _nvc_CompanyHomePage;
		
		private string _nvc_LinkName;
		
		private string _nvc_LinkManFax;
		
		private string _nvc_LinkManQQ;
		
		private string _nvc_LinkManSKYPE;
		
		private string _nvc_LinkManMSN;
		
		private decimal _dm_YuFuKuan;
		
		private decimal _dm_YuE;
		
		private decimal _dm_QianFei;
		
		private string _nvc_Power;
		
		private int _i_PowerDaZhe;
		
		private int _i_PowerJiFen;
		
		private string _nt_BeiZhu;
		
		private int _i_IntegralMobileId;
		
		private int _i_IsSend;
		
		private string _nt_BYEmail;
		
		private string _nvc_ZhuTiFile;
		
		private int _i_ReceiveEmail;
		
		private string _nvc_Flag;
		
		private EntitySet<t_ReceiveAddress> _t_ReceiveAddress;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Onnvc_UserNumChanging(string value);
    partial void Onnvc_UserNumChanged();
    partial void Onnvc_NameChanging(string value);
    partial void Onnvc_NameChanged();
    partial void Onnvc_EnNameChanging(string value);
    partial void Onnvc_EnNameChanged();
    partial void Onnvc_CompanyChanging(string value);
    partial void Onnvc_CompanyChanged();
    partial void Onnvc_EnCompanyChanging(string value);
    partial void Onnvc_EnCompanyChanged();
    partial void Onnvc_DaiLiNameChanging(string value);
    partial void Onnvc_DaiLiNameChanged();
    partial void Onnvc_RealNameChanging(string value);
    partial void Onnvc_RealNameChanged();
    partial void Onnvc_FaxNumberChanging(string value);
    partial void Onnvc_FaxNumberChanged();
    partial void Onnvc_PassWordChanging(string value);
    partial void Onnvc_PassWordChanged();
    partial void Onnvc_IDCardChanging(string value);
    partial void Onnvc_IDCardChanged();
    partial void Onnvc_TitlePhotoChanging(string value);
    partial void Onnvc_TitlePhotoChanged();
    partial void Oni_CountryIdChanging(System.Nullable<int> value);
    partial void Oni_CountryIdChanged();
    partial void Oni_UserTypeIdChanging(System.Nullable<int> value);
    partial void Oni_UserTypeIdChanged();
    partial void Oni_RegTypeIdChanging(System.Nullable<int> value);
    partial void Oni_RegTypeIdChanged();
    partial void Oni_GradeChanging(int value);
    partial void Oni_GradeChanged();
    partial void Oni_GuoJiIdChanging(int value);
    partial void Oni_GuoJiIdChanged();
    partial void Oni_ProvinceIdChanging(int value);
    partial void Oni_ProvinceIdChanged();
    partial void Oni_CityIdChanging(int value);
    partial void Oni_CityIdChanged();
    partial void Oni_AreaIdChanging(int value);
    partial void Oni_AreaIdChanged();
    partial void Onnvc_AddressChanging(string value);
    partial void Onnvc_AddressChanged();
    partial void Onnvc_EnAddressChanging(string value);
    partial void Onnvc_EnAddressChanged();
    partial void Onnvc_ZipCodeChanging(string value);
    partial void Onnvc_ZipCodeChanged();
    partial void Onnvc_MobilePhoneChanging(string value);
    partial void Onnvc_MobilePhoneChanged();
    partial void Onnvc_TelPhoneChanging(string value);
    partial void Onnvc_TelPhoneChanged();
    partial void Onnvc_EmailChanging(string value);
    partial void Onnvc_EmailChanged();
    partial void Oni_DefaultAddressChanging(int value);
    partial void Oni_DefaultAddressChanged();
    partial void Oni_SexChanging(int value);
    partial void Oni_SexChanged();
    partial void Onnvc_AgeChanging(string value);
    partial void Onnvc_AgeChanged();
    partial void Onnvc_IPChanging(string value);
    partial void Onnvc_IPChanged();
    partial void Oni_IntegralChanging(int value);
    partial void Oni_IntegralChanged();
    partial void Oni_PleaseChanging(int value);
    partial void Oni_PleaseChanged();
    partial void Ondt_AddTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_AddTimeChanged();
    partial void Onis_alipayChanging(System.Nullable<int> value);
    partial void Onis_alipayChanged();
    partial void Ontext_passChanging(string value);
    partial void Ontext_passChanged();
    partial void Ondm_MoneyChanging(System.Nullable<decimal> value);
    partial void Ondm_MoneyChanged();
    partial void Onnvc_PersonalizedChanging(string value);
    partial void Onnvc_PersonalizedChanged();
    partial void Oni_MemberTypeChanging(int value);
    partial void Oni_MemberTypeChanged();
    partial void Onnvc_EnglishNameChanging(string value);
    partial void Onnvc_EnglishNameChanged();
    partial void Onnvc_CompanyHomePageChanging(string value);
    partial void Onnvc_CompanyHomePageChanged();
    partial void Onnvc_LinkNameChanging(string value);
    partial void Onnvc_LinkNameChanged();
    partial void Onnvc_LinkManFaxChanging(string value);
    partial void Onnvc_LinkManFaxChanged();
    partial void Onnvc_LinkManQQChanging(string value);
    partial void Onnvc_LinkManQQChanged();
    partial void Onnvc_LinkManSKYPEChanging(string value);
    partial void Onnvc_LinkManSKYPEChanged();
    partial void Onnvc_LinkManMSNChanging(string value);
    partial void Onnvc_LinkManMSNChanged();
    partial void Ondm_YuFuKuanChanging(decimal value);
    partial void Ondm_YuFuKuanChanged();
    partial void Ondm_YuEChanging(decimal value);
    partial void Ondm_YuEChanged();
    partial void Ondm_QianFeiChanging(decimal value);
    partial void Ondm_QianFeiChanged();
    partial void Onnvc_PowerChanging(string value);
    partial void Onnvc_PowerChanged();
    partial void Oni_PowerDaZheChanging(int value);
    partial void Oni_PowerDaZheChanged();
    partial void Oni_PowerJiFenChanging(int value);
    partial void Oni_PowerJiFenChanged();
    partial void Onnt_BeiZhuChanging(string value);
    partial void Onnt_BeiZhuChanged();
    partial void Oni_IntegralMobileIdChanging(int value);
    partial void Oni_IntegralMobileIdChanged();
    partial void Oni_IsSendChanging(int value);
    partial void Oni_IsSendChanged();
    partial void Onnt_BYEmailChanging(string value);
    partial void Onnt_BYEmailChanged();
    partial void Onnvc_ZhuTiFileChanging(string value);
    partial void Onnvc_ZhuTiFileChanged();
    partial void Oni_ReceiveEmailChanging(int value);
    partial void Oni_ReceiveEmailChanged();
    partial void Onnvc_FlagChanging(string value);
    partial void Onnvc_FlagChanged();
    #endregion
		
		public t_Member()
		{
			this._t_ReceiveAddress = new EntitySet<t_ReceiveAddress>(new Action<t_ReceiveAddress>(this.attach_t_ReceiveAddress), new Action<t_ReceiveAddress>(this.detach_t_ReceiveAddress));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_UserNum", DbType="NVarChar(50)")]
		public string nvc_UserNum
		{
			get
			{
				return this._nvc_UserNum;
			}
			set
			{
				if ((this._nvc_UserNum != value))
				{
					this.Onnvc_UserNumChanging(value);
					this.SendPropertyChanging();
					this._nvc_UserNum = value;
					this.SendPropertyChanged("nvc_UserNum");
					this.Onnvc_UserNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Name", DbType="NVarChar(50)")]
		public string nvc_Name
		{
			get
			{
				return this._nvc_Name;
			}
			set
			{
				if ((this._nvc_Name != value))
				{
					this.Onnvc_NameChanging(value);
					this.SendPropertyChanging();
					this._nvc_Name = value;
					this.SendPropertyChanged("nvc_Name");
					this.Onnvc_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_EnName", DbType="NVarChar(50)")]
		public string nvc_EnName
		{
			get
			{
				return this._nvc_EnName;
			}
			set
			{
				if ((this._nvc_EnName != value))
				{
					this.Onnvc_EnNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_EnName = value;
					this.SendPropertyChanged("nvc_EnName");
					this.Onnvc_EnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Company", DbType="NVarChar(50)")]
		public string nvc_Company
		{
			get
			{
				return this._nvc_Company;
			}
			set
			{
				if ((this._nvc_Company != value))
				{
					this.Onnvc_CompanyChanging(value);
					this.SendPropertyChanging();
					this._nvc_Company = value;
					this.SendPropertyChanged("nvc_Company");
					this.Onnvc_CompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_EnCompany", DbType="NVarChar(50)")]
		public string nvc_EnCompany
		{
			get
			{
				return this._nvc_EnCompany;
			}
			set
			{
				if ((this._nvc_EnCompany != value))
				{
					this.Onnvc_EnCompanyChanging(value);
					this.SendPropertyChanging();
					this._nvc_EnCompany = value;
					this.SendPropertyChanged("nvc_EnCompany");
					this.Onnvc_EnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_DaiLiName", DbType="NVarChar(50)")]
		public string nvc_DaiLiName
		{
			get
			{
				return this._nvc_DaiLiName;
			}
			set
			{
				if ((this._nvc_DaiLiName != value))
				{
					this.Onnvc_DaiLiNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_DaiLiName = value;
					this.SendPropertyChanged("nvc_DaiLiName");
					this.Onnvc_DaiLiNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_RealName", DbType="NVarChar(50)")]
		public string nvc_RealName
		{
			get
			{
				return this._nvc_RealName;
			}
			set
			{
				if ((this._nvc_RealName != value))
				{
					this.Onnvc_RealNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_RealName = value;
					this.SendPropertyChanged("nvc_RealName");
					this.Onnvc_RealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_FaxNumber", DbType="NVarChar(50)")]
		public string nvc_FaxNumber
		{
			get
			{
				return this._nvc_FaxNumber;
			}
			set
			{
				if ((this._nvc_FaxNumber != value))
				{
					this.Onnvc_FaxNumberChanging(value);
					this.SendPropertyChanging();
					this._nvc_FaxNumber = value;
					this.SendPropertyChanged("nvc_FaxNumber");
					this.Onnvc_FaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_PassWord", DbType="NVarChar(50)")]
		public string nvc_PassWord
		{
			get
			{
				return this._nvc_PassWord;
			}
			set
			{
				if ((this._nvc_PassWord != value))
				{
					this.Onnvc_PassWordChanging(value);
					this.SendPropertyChanging();
					this._nvc_PassWord = value;
					this.SendPropertyChanged("nvc_PassWord");
					this.Onnvc_PassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_IDCard", DbType="NVarChar(50)")]
		public string nvc_IDCard
		{
			get
			{
				return this._nvc_IDCard;
			}
			set
			{
				if ((this._nvc_IDCard != value))
				{
					this.Onnvc_IDCardChanging(value);
					this.SendPropertyChanging();
					this._nvc_IDCard = value;
					this.SendPropertyChanged("nvc_IDCard");
					this.Onnvc_IDCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_TitlePhoto", DbType="NVarChar(100)")]
		public string nvc_TitlePhoto
		{
			get
			{
				return this._nvc_TitlePhoto;
			}
			set
			{
				if ((this._nvc_TitlePhoto != value))
				{
					this.Onnvc_TitlePhotoChanging(value);
					this.SendPropertyChanging();
					this._nvc_TitlePhoto = value;
					this.SendPropertyChanged("nvc_TitlePhoto");
					this.Onnvc_TitlePhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_CountryId", DbType="Int")]
		public System.Nullable<int> i_CountryId
		{
			get
			{
				return this._i_CountryId;
			}
			set
			{
				if ((this._i_CountryId != value))
				{
					this.Oni_CountryIdChanging(value);
					this.SendPropertyChanging();
					this._i_CountryId = value;
					this.SendPropertyChanged("i_CountryId");
					this.Oni_CountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_UserTypeId", DbType="Int")]
		public System.Nullable<int> i_UserTypeId
		{
			get
			{
				return this._i_UserTypeId;
			}
			set
			{
				if ((this._i_UserTypeId != value))
				{
					this.Oni_UserTypeIdChanging(value);
					this.SendPropertyChanging();
					this._i_UserTypeId = value;
					this.SendPropertyChanged("i_UserTypeId");
					this.Oni_UserTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_RegTypeId", DbType="Int")]
		public System.Nullable<int> i_RegTypeId
		{
			get
			{
				return this._i_RegTypeId;
			}
			set
			{
				if ((this._i_RegTypeId != value))
				{
					this.Oni_RegTypeIdChanging(value);
					this.SendPropertyChanging();
					this._i_RegTypeId = value;
					this.SendPropertyChanged("i_RegTypeId");
					this.Oni_RegTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Grade", DbType="Int NOT NULL")]
		public int i_Grade
		{
			get
			{
				return this._i_Grade;
			}
			set
			{
				if ((this._i_Grade != value))
				{
					this.Oni_GradeChanging(value);
					this.SendPropertyChanging();
					this._i_Grade = value;
					this.SendPropertyChanged("i_Grade");
					this.Oni_GradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_GuoJiId", DbType="Int NOT NULL")]
		public int i_GuoJiId
		{
			get
			{
				return this._i_GuoJiId;
			}
			set
			{
				if ((this._i_GuoJiId != value))
				{
					this.Oni_GuoJiIdChanging(value);
					this.SendPropertyChanging();
					this._i_GuoJiId = value;
					this.SendPropertyChanged("i_GuoJiId");
					this.Oni_GuoJiIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ProvinceId", DbType="Int NOT NULL")]
		public int i_ProvinceId
		{
			get
			{
				return this._i_ProvinceId;
			}
			set
			{
				if ((this._i_ProvinceId != value))
				{
					this.Oni_ProvinceIdChanging(value);
					this.SendPropertyChanging();
					this._i_ProvinceId = value;
					this.SendPropertyChanged("i_ProvinceId");
					this.Oni_ProvinceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_CityId", DbType="Int NOT NULL")]
		public int i_CityId
		{
			get
			{
				return this._i_CityId;
			}
			set
			{
				if ((this._i_CityId != value))
				{
					this.Oni_CityIdChanging(value);
					this.SendPropertyChanging();
					this._i_CityId = value;
					this.SendPropertyChanged("i_CityId");
					this.Oni_CityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_AreaId", DbType="Int NOT NULL")]
		public int i_AreaId
		{
			get
			{
				return this._i_AreaId;
			}
			set
			{
				if ((this._i_AreaId != value))
				{
					this.Oni_AreaIdChanging(value);
					this.SendPropertyChanging();
					this._i_AreaId = value;
					this.SendPropertyChanged("i_AreaId");
					this.Oni_AreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Address", DbType="NVarChar(500)")]
		public string nvc_Address
		{
			get
			{
				return this._nvc_Address;
			}
			set
			{
				if ((this._nvc_Address != value))
				{
					this.Onnvc_AddressChanging(value);
					this.SendPropertyChanging();
					this._nvc_Address = value;
					this.SendPropertyChanged("nvc_Address");
					this.Onnvc_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_EnAddress", DbType="NVarChar(500)")]
		public string nvc_EnAddress
		{
			get
			{
				return this._nvc_EnAddress;
			}
			set
			{
				if ((this._nvc_EnAddress != value))
				{
					this.Onnvc_EnAddressChanging(value);
					this.SendPropertyChanging();
					this._nvc_EnAddress = value;
					this.SendPropertyChanged("nvc_EnAddress");
					this.Onnvc_EnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_ZipCode", DbType="NVarChar(50)")]
		public string nvc_ZipCode
		{
			get
			{
				return this._nvc_ZipCode;
			}
			set
			{
				if ((this._nvc_ZipCode != value))
				{
					this.Onnvc_ZipCodeChanging(value);
					this.SendPropertyChanging();
					this._nvc_ZipCode = value;
					this.SendPropertyChanged("nvc_ZipCode");
					this.Onnvc_ZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_MobilePhone", DbType="NVarChar(50)")]
		public string nvc_MobilePhone
		{
			get
			{
				return this._nvc_MobilePhone;
			}
			set
			{
				if ((this._nvc_MobilePhone != value))
				{
					this.Onnvc_MobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_MobilePhone = value;
					this.SendPropertyChanged("nvc_MobilePhone");
					this.Onnvc_MobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_TelPhone", DbType="NVarChar(50)")]
		public string nvc_TelPhone
		{
			get
			{
				return this._nvc_TelPhone;
			}
			set
			{
				if ((this._nvc_TelPhone != value))
				{
					this.Onnvc_TelPhoneChanging(value);
					this.SendPropertyChanging();
					this._nvc_TelPhone = value;
					this.SendPropertyChanged("nvc_TelPhone");
					this.Onnvc_TelPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Email", DbType="NVarChar(50)")]
		public string nvc_Email
		{
			get
			{
				return this._nvc_Email;
			}
			set
			{
				if ((this._nvc_Email != value))
				{
					this.Onnvc_EmailChanging(value);
					this.SendPropertyChanging();
					this._nvc_Email = value;
					this.SendPropertyChanged("nvc_Email");
					this.Onnvc_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_DefaultAddress", DbType="Int NOT NULL")]
		public int i_DefaultAddress
		{
			get
			{
				return this._i_DefaultAddress;
			}
			set
			{
				if ((this._i_DefaultAddress != value))
				{
					this.Oni_DefaultAddressChanging(value);
					this.SendPropertyChanging();
					this._i_DefaultAddress = value;
					this.SendPropertyChanged("i_DefaultAddress");
					this.Oni_DefaultAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Sex", DbType="Int NOT NULL")]
		public int i_Sex
		{
			get
			{
				return this._i_Sex;
			}
			set
			{
				if ((this._i_Sex != value))
				{
					this.Oni_SexChanging(value);
					this.SendPropertyChanging();
					this._i_Sex = value;
					this.SendPropertyChanged("i_Sex");
					this.Oni_SexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Age", DbType="NVarChar(50)")]
		public string nvc_Age
		{
			get
			{
				return this._nvc_Age;
			}
			set
			{
				if ((this._nvc_Age != value))
				{
					this.Onnvc_AgeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Age = value;
					this.SendPropertyChanged("nvc_Age");
					this.Onnvc_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_IP", DbType="NVarChar(50)")]
		public string nvc_IP
		{
			get
			{
				return this._nvc_IP;
			}
			set
			{
				if ((this._nvc_IP != value))
				{
					this.Onnvc_IPChanging(value);
					this.SendPropertyChanging();
					this._nvc_IP = value;
					this.SendPropertyChanged("nvc_IP");
					this.Onnvc_IPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Integral", DbType="Int NOT NULL")]
		public int i_Integral
		{
			get
			{
				return this._i_Integral;
			}
			set
			{
				if ((this._i_Integral != value))
				{
					this.Oni_IntegralChanging(value);
					this.SendPropertyChanging();
					this._i_Integral = value;
					this.SendPropertyChanged("i_Integral");
					this.Oni_IntegralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Please", DbType="Int NOT NULL")]
		public int i_Please
		{
			get
			{
				return this._i_Please;
			}
			set
			{
				if ((this._i_Please != value))
				{
					this.Oni_PleaseChanging(value);
					this.SendPropertyChanging();
					this._i_Please = value;
					this.SendPropertyChanged("i_Please");
					this.Oni_PleaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_alipay", DbType="Int")]
		public System.Nullable<int> is_alipay
		{
			get
			{
				return this._is_alipay;
			}
			set
			{
				if ((this._is_alipay != value))
				{
					this.Onis_alipayChanging(value);
					this.SendPropertyChanging();
					this._is_alipay = value;
					this.SendPropertyChanged("is_alipay");
					this.Onis_alipayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text_pass", DbType="NVarChar(50)")]
		public string text_pass
		{
			get
			{
				return this._text_pass;
			}
			set
			{
				if ((this._text_pass != value))
				{
					this.Ontext_passChanging(value);
					this.SendPropertyChanging();
					this._text_pass = value;
					this.SendPropertyChanged("text_pass");
					this.Ontext_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_Money", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> dm_Money
		{
			get
			{
				return this._dm_Money;
			}
			set
			{
				if ((this._dm_Money != value))
				{
					this.Ondm_MoneyChanging(value);
					this.SendPropertyChanging();
					this._dm_Money = value;
					this.SendPropertyChanged("dm_Money");
					this.Ondm_MoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Personalized", DbType="NVarChar(250)")]
		public string nvc_Personalized
		{
			get
			{
				return this._nvc_Personalized;
			}
			set
			{
				if ((this._nvc_Personalized != value))
				{
					this.Onnvc_PersonalizedChanging(value);
					this.SendPropertyChanging();
					this._nvc_Personalized = value;
					this.SendPropertyChanged("nvc_Personalized");
					this.Onnvc_PersonalizedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberType", DbType="Int NOT NULL")]
		public int i_MemberType
		{
			get
			{
				return this._i_MemberType;
			}
			set
			{
				if ((this._i_MemberType != value))
				{
					this.Oni_MemberTypeChanging(value);
					this.SendPropertyChanging();
					this._i_MemberType = value;
					this.SendPropertyChanged("i_MemberType");
					this.Oni_MemberTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_EnglishName", DbType="NVarChar(200)")]
		public string nvc_EnglishName
		{
			get
			{
				return this._nvc_EnglishName;
			}
			set
			{
				if ((this._nvc_EnglishName != value))
				{
					this.Onnvc_EnglishNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_EnglishName = value;
					this.SendPropertyChanged("nvc_EnglishName");
					this.Onnvc_EnglishNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_CompanyHomePage", DbType="NVarChar(500)")]
		public string nvc_CompanyHomePage
		{
			get
			{
				return this._nvc_CompanyHomePage;
			}
			set
			{
				if ((this._nvc_CompanyHomePage != value))
				{
					this.Onnvc_CompanyHomePageChanging(value);
					this.SendPropertyChanging();
					this._nvc_CompanyHomePage = value;
					this.SendPropertyChanged("nvc_CompanyHomePage");
					this.Onnvc_CompanyHomePageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_LinkName", DbType="NVarChar(50)")]
		public string nvc_LinkName
		{
			get
			{
				return this._nvc_LinkName;
			}
			set
			{
				if ((this._nvc_LinkName != value))
				{
					this.Onnvc_LinkNameChanging(value);
					this.SendPropertyChanging();
					this._nvc_LinkName = value;
					this.SendPropertyChanged("nvc_LinkName");
					this.Onnvc_LinkNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_LinkManFax", DbType="NVarChar(50)")]
		public string nvc_LinkManFax
		{
			get
			{
				return this._nvc_LinkManFax;
			}
			set
			{
				if ((this._nvc_LinkManFax != value))
				{
					this.Onnvc_LinkManFaxChanging(value);
					this.SendPropertyChanging();
					this._nvc_LinkManFax = value;
					this.SendPropertyChanged("nvc_LinkManFax");
					this.Onnvc_LinkManFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_LinkManQQ", DbType="NVarChar(50)")]
		public string nvc_LinkManQQ
		{
			get
			{
				return this._nvc_LinkManQQ;
			}
			set
			{
				if ((this._nvc_LinkManQQ != value))
				{
					this.Onnvc_LinkManQQChanging(value);
					this.SendPropertyChanging();
					this._nvc_LinkManQQ = value;
					this.SendPropertyChanged("nvc_LinkManQQ");
					this.Onnvc_LinkManQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_LinkManSKYPE", DbType="NVarChar(50)")]
		public string nvc_LinkManSKYPE
		{
			get
			{
				return this._nvc_LinkManSKYPE;
			}
			set
			{
				if ((this._nvc_LinkManSKYPE != value))
				{
					this.Onnvc_LinkManSKYPEChanging(value);
					this.SendPropertyChanging();
					this._nvc_LinkManSKYPE = value;
					this.SendPropertyChanged("nvc_LinkManSKYPE");
					this.Onnvc_LinkManSKYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_LinkManMSN", DbType="NVarChar(50)")]
		public string nvc_LinkManMSN
		{
			get
			{
				return this._nvc_LinkManMSN;
			}
			set
			{
				if ((this._nvc_LinkManMSN != value))
				{
					this.Onnvc_LinkManMSNChanging(value);
					this.SendPropertyChanging();
					this._nvc_LinkManMSN = value;
					this.SendPropertyChanged("nvc_LinkManMSN");
					this.Onnvc_LinkManMSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_YuFuKuan", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_YuFuKuan
		{
			get
			{
				return this._dm_YuFuKuan;
			}
			set
			{
				if ((this._dm_YuFuKuan != value))
				{
					this.Ondm_YuFuKuanChanging(value);
					this.SendPropertyChanging();
					this._dm_YuFuKuan = value;
					this.SendPropertyChanged("dm_YuFuKuan");
					this.Ondm_YuFuKuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_YuE", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_YuE
		{
			get
			{
				return this._dm_YuE;
			}
			set
			{
				if ((this._dm_YuE != value))
				{
					this.Ondm_YuEChanging(value);
					this.SendPropertyChanging();
					this._dm_YuE = value;
					this.SendPropertyChanged("dm_YuE");
					this.Ondm_YuEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_QianFei", DbType="Decimal(18,2) NOT NULL")]
		public decimal dm_QianFei
		{
			get
			{
				return this._dm_QianFei;
			}
			set
			{
				if ((this._dm_QianFei != value))
				{
					this.Ondm_QianFeiChanging(value);
					this.SendPropertyChanging();
					this._dm_QianFei = value;
					this.SendPropertyChanged("dm_QianFei");
					this.Ondm_QianFeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Power", DbType="NVarChar(50)")]
		public string nvc_Power
		{
			get
			{
				return this._nvc_Power;
			}
			set
			{
				if ((this._nvc_Power != value))
				{
					this.Onnvc_PowerChanging(value);
					this.SendPropertyChanging();
					this._nvc_Power = value;
					this.SendPropertyChanged("nvc_Power");
					this.Onnvc_PowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_PowerDaZhe", DbType="Int NOT NULL")]
		public int i_PowerDaZhe
		{
			get
			{
				return this._i_PowerDaZhe;
			}
			set
			{
				if ((this._i_PowerDaZhe != value))
				{
					this.Oni_PowerDaZheChanging(value);
					this.SendPropertyChanging();
					this._i_PowerDaZhe = value;
					this.SendPropertyChanged("i_PowerDaZhe");
					this.Oni_PowerDaZheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_PowerJiFen", DbType="Int NOT NULL")]
		public int i_PowerJiFen
		{
			get
			{
				return this._i_PowerJiFen;
			}
			set
			{
				if ((this._i_PowerJiFen != value))
				{
					this.Oni_PowerJiFenChanging(value);
					this.SendPropertyChanging();
					this._i_PowerJiFen = value;
					this.SendPropertyChanged("i_PowerJiFen");
					this.Oni_PowerJiFenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nt_BeiZhu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string nt_BeiZhu
		{
			get
			{
				return this._nt_BeiZhu;
			}
			set
			{
				if ((this._nt_BeiZhu != value))
				{
					this.Onnt_BeiZhuChanging(value);
					this.SendPropertyChanging();
					this._nt_BeiZhu = value;
					this.SendPropertyChanged("nt_BeiZhu");
					this.Onnt_BeiZhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IntegralMobileId", DbType="Int NOT NULL")]
		public int i_IntegralMobileId
		{
			get
			{
				return this._i_IntegralMobileId;
			}
			set
			{
				if ((this._i_IntegralMobileId != value))
				{
					this.Oni_IntegralMobileIdChanging(value);
					this.SendPropertyChanging();
					this._i_IntegralMobileId = value;
					this.SendPropertyChanged("i_IntegralMobileId");
					this.Oni_IntegralMobileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IsSend", DbType="Int NOT NULL")]
		public int i_IsSend
		{
			get
			{
				return this._i_IsSend;
			}
			set
			{
				if ((this._i_IsSend != value))
				{
					this.Oni_IsSendChanging(value);
					this.SendPropertyChanging();
					this._i_IsSend = value;
					this.SendPropertyChanged("i_IsSend");
					this.Oni_IsSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nt_BYEmail", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string nt_BYEmail
		{
			get
			{
				return this._nt_BYEmail;
			}
			set
			{
				if ((this._nt_BYEmail != value))
				{
					this.Onnt_BYEmailChanging(value);
					this.SendPropertyChanging();
					this._nt_BYEmail = value;
					this.SendPropertyChanged("nt_BYEmail");
					this.Onnt_BYEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_ZhuTiFile", DbType="NVarChar(150)")]
		public string nvc_ZhuTiFile
		{
			get
			{
				return this._nvc_ZhuTiFile;
			}
			set
			{
				if ((this._nvc_ZhuTiFile != value))
				{
					this.Onnvc_ZhuTiFileChanging(value);
					this.SendPropertyChanging();
					this._nvc_ZhuTiFile = value;
					this.SendPropertyChanged("nvc_ZhuTiFile");
					this.Onnvc_ZhuTiFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ReceiveEmail", DbType="Int NOT NULL")]
		public int i_ReceiveEmail
		{
			get
			{
				return this._i_ReceiveEmail;
			}
			set
			{
				if ((this._i_ReceiveEmail != value))
				{
					this.Oni_ReceiveEmailChanging(value);
					this.SendPropertyChanging();
					this._i_ReceiveEmail = value;
					this.SendPropertyChanged("i_ReceiveEmail");
					this.Oni_ReceiveEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Flag", DbType="NVarChar(200)")]
		public string nvc_Flag
		{
			get
			{
				return this._nvc_Flag;
			}
			set
			{
				if ((this._nvc_Flag != value))
				{
					this.Onnvc_FlagChanging(value);
					this.SendPropertyChanging();
					this._nvc_Flag = value;
					this.SendPropertyChanged("nvc_Flag");
					this.Onnvc_FlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Member_t_ReceiveAddress", Storage="_t_ReceiveAddress", ThisKey="i_Id", OtherKey="i_MemberId")]
		public EntitySet<t_ReceiveAddress> t_ReceiveAddress
		{
			get
			{
				return this._t_ReceiveAddress;
			}
			set
			{
				this._t_ReceiveAddress.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_t_ReceiveAddress(t_ReceiveAddress entity)
		{
			this.SendPropertyChanging();
			entity.t_Member = this;
		}
		
		private void detach_t_ReceiveAddress(t_ReceiveAddress entity)
		{
			this.SendPropertyChanging();
			entity.t_Member = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_MemberGrade")]
	public partial class t_MemberGrade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_id;
		
		private string _nvc_Name;
		
		private int _i_Grade;
		
		private System.Nullable<int> _i_Discount;
		
		private int _i_ZhuanliNum;
		
		private int _i_ShangbiaoNum;
		
		private int _i_QDNumber;
		
		private string _nvc_Logo;
		
		private string _nvc_Name_en;
		
		private string _nvc_Name_kr;
		
		private string _nvc_Name_jp;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_idChanging(int value);
    partial void Oni_idChanged();
    partial void Onnvc_NameChanging(string value);
    partial void Onnvc_NameChanged();
    partial void Oni_GradeChanging(int value);
    partial void Oni_GradeChanged();
    partial void Oni_DiscountChanging(System.Nullable<int> value);
    partial void Oni_DiscountChanged();
    partial void Oni_ZhuanliNumChanging(int value);
    partial void Oni_ZhuanliNumChanged();
    partial void Oni_ShangbiaoNumChanging(int value);
    partial void Oni_ShangbiaoNumChanged();
    partial void Oni_QDNumberChanging(int value);
    partial void Oni_QDNumberChanged();
    partial void Onnvc_LogoChanging(string value);
    partial void Onnvc_LogoChanged();
    partial void Onnvc_Name_enChanging(string value);
    partial void Onnvc_Name_enChanged();
    partial void Onnvc_Name_krChanging(string value);
    partial void Onnvc_Name_krChanged();
    partial void Onnvc_Name_jpChanging(string value);
    partial void Onnvc_Name_jpChanged();
    #endregion
		
		public t_MemberGrade()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_id
		{
			get
			{
				return this._i_id;
			}
			set
			{
				if ((this._i_id != value))
				{
					this.Oni_idChanging(value);
					this.SendPropertyChanging();
					this._i_id = value;
					this.SendPropertyChanged("i_id");
					this.Oni_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Name", DbType="NVarChar(50)")]
		public string nvc_Name
		{
			get
			{
				return this._nvc_Name;
			}
			set
			{
				if ((this._nvc_Name != value))
				{
					this.Onnvc_NameChanging(value);
					this.SendPropertyChanging();
					this._nvc_Name = value;
					this.SendPropertyChanged("nvc_Name");
					this.Onnvc_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Grade", DbType="Int NOT NULL")]
		public int i_Grade
		{
			get
			{
				return this._i_Grade;
			}
			set
			{
				if ((this._i_Grade != value))
				{
					this.Oni_GradeChanging(value);
					this.SendPropertyChanging();
					this._i_Grade = value;
					this.SendPropertyChanged("i_Grade");
					this.Oni_GradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Discount", DbType="Int")]
		public System.Nullable<int> i_Discount
		{
			get
			{
				return this._i_Discount;
			}
			set
			{
				if ((this._i_Discount != value))
				{
					this.Oni_DiscountChanging(value);
					this.SendPropertyChanging();
					this._i_Discount = value;
					this.SendPropertyChanged("i_Discount");
					this.Oni_DiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ZhuanliNum", DbType="Int NOT NULL")]
		public int i_ZhuanliNum
		{
			get
			{
				return this._i_ZhuanliNum;
			}
			set
			{
				if ((this._i_ZhuanliNum != value))
				{
					this.Oni_ZhuanliNumChanging(value);
					this.SendPropertyChanging();
					this._i_ZhuanliNum = value;
					this.SendPropertyChanged("i_ZhuanliNum");
					this.Oni_ZhuanliNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ShangbiaoNum", DbType="Int NOT NULL")]
		public int i_ShangbiaoNum
		{
			get
			{
				return this._i_ShangbiaoNum;
			}
			set
			{
				if ((this._i_ShangbiaoNum != value))
				{
					this.Oni_ShangbiaoNumChanging(value);
					this.SendPropertyChanging();
					this._i_ShangbiaoNum = value;
					this.SendPropertyChanged("i_ShangbiaoNum");
					this.Oni_ShangbiaoNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_QDNumber", DbType="Int NOT NULL")]
		public int i_QDNumber
		{
			get
			{
				return this._i_QDNumber;
			}
			set
			{
				if ((this._i_QDNumber != value))
				{
					this.Oni_QDNumberChanging(value);
					this.SendPropertyChanging();
					this._i_QDNumber = value;
					this.SendPropertyChanged("i_QDNumber");
					this.Oni_QDNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Logo", DbType="NVarChar(50)")]
		public string nvc_Logo
		{
			get
			{
				return this._nvc_Logo;
			}
			set
			{
				if ((this._nvc_Logo != value))
				{
					this.Onnvc_LogoChanging(value);
					this.SendPropertyChanging();
					this._nvc_Logo = value;
					this.SendPropertyChanged("nvc_Logo");
					this.Onnvc_LogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Name_en", DbType="NVarChar(50)")]
		public string nvc_Name_en
		{
			get
			{
				return this._nvc_Name_en;
			}
			set
			{
				if ((this._nvc_Name_en != value))
				{
					this.Onnvc_Name_enChanging(value);
					this.SendPropertyChanging();
					this._nvc_Name_en = value;
					this.SendPropertyChanged("nvc_Name_en");
					this.Onnvc_Name_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Name_kr", DbType="NVarChar(50)")]
		public string nvc_Name_kr
		{
			get
			{
				return this._nvc_Name_kr;
			}
			set
			{
				if ((this._nvc_Name_kr != value))
				{
					this.Onnvc_Name_krChanging(value);
					this.SendPropertyChanging();
					this._nvc_Name_kr = value;
					this.SendPropertyChanged("nvc_Name_kr");
					this.Onnvc_Name_krChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Name_jp", DbType="NVarChar(50)")]
		public string nvc_Name_jp
		{
			get
			{
				return this._nvc_Name_jp;
			}
			set
			{
				if ((this._nvc_Name_jp != value))
				{
					this.Onnvc_Name_jpChanging(value);
					this.SendPropertyChanging();
					this._nvc_Name_jp = value;
					this.SendPropertyChanged("nvc_Name_jp");
					this.Onnvc_Name_jpChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Coupon")]
	public partial class t_Coupon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private string _nvc_Code;
		
		private int _i_Type;
		
		private int _i_State;
		
		private System.Nullable<System.DateTime> _dt_AddTime;
		
		private System.Nullable<System.DateTime> _dt_ExpireTime;
		
		private System.Nullable<System.DateTime> _dt_UpdateStateTime;
		
		private int _i_MemberId;
		
		private string _nvc_From;
		
		private string _nvc_OrderNumber;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Onnvc_CodeChanging(string value);
    partial void Onnvc_CodeChanged();
    partial void Oni_TypeChanging(int value);
    partial void Oni_TypeChanged();
    partial void Oni_StateChanging(int value);
    partial void Oni_StateChanged();
    partial void Ondt_AddTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_AddTimeChanged();
    partial void Ondt_ExpireTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_ExpireTimeChanged();
    partial void Ondt_UpdateStateTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_UpdateStateTimeChanged();
    partial void Oni_MemberIdChanging(int value);
    partial void Oni_MemberIdChanged();
    partial void Onnvc_FromChanging(string value);
    partial void Onnvc_FromChanged();
    partial void Onnvc_OrderNumberChanging(string value);
    partial void Onnvc_OrderNumberChanged();
    #endregion
		
		public t_Coupon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Code", DbType="NVarChar(50)")]
		public string nvc_Code
		{
			get
			{
				return this._nvc_Code;
			}
			set
			{
				if ((this._nvc_Code != value))
				{
					this.Onnvc_CodeChanging(value);
					this.SendPropertyChanging();
					this._nvc_Code = value;
					this.SendPropertyChanged("nvc_Code");
					this.Onnvc_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Type", DbType="Int NOT NULL")]
		public int i_Type
		{
			get
			{
				return this._i_Type;
			}
			set
			{
				if ((this._i_Type != value))
				{
					this.Oni_TypeChanging(value);
					this.SendPropertyChanging();
					this._i_Type = value;
					this.SendPropertyChanged("i_Type");
					this.Oni_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_State", DbType="Int NOT NULL")]
		public int i_State
		{
			get
			{
				return this._i_State;
			}
			set
			{
				if ((this._i_State != value))
				{
					this.Oni_StateChanging(value);
					this.SendPropertyChanging();
					this._i_State = value;
					this.SendPropertyChanged("i_State");
					this.Oni_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_ExpireTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_ExpireTime
		{
			get
			{
				return this._dt_ExpireTime;
			}
			set
			{
				if ((this._dt_ExpireTime != value))
				{
					this.Ondt_ExpireTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_ExpireTime = value;
					this.SendPropertyChanged("dt_ExpireTime");
					this.Ondt_ExpireTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_UpdateStateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_UpdateStateTime
		{
			get
			{
				return this._dt_UpdateStateTime;
			}
			set
			{
				if ((this._dt_UpdateStateTime != value))
				{
					this.Ondt_UpdateStateTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_UpdateStateTime = value;
					this.SendPropertyChanged("dt_UpdateStateTime");
					this.Ondt_UpdateStateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberId", DbType="Int NOT NULL")]
		public int i_MemberId
		{
			get
			{
				return this._i_MemberId;
			}
			set
			{
				if ((this._i_MemberId != value))
				{
					this.Oni_MemberIdChanging(value);
					this.SendPropertyChanging();
					this._i_MemberId = value;
					this.SendPropertyChanged("i_MemberId");
					this.Oni_MemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_From", DbType="NVarChar(50)")]
		public string nvc_From
		{
			get
			{
				return this._nvc_From;
			}
			set
			{
				if ((this._nvc_From != value))
				{
					this.Onnvc_FromChanging(value);
					this.SendPropertyChanging();
					this._nvc_From = value;
					this.SendPropertyChanged("nvc_From");
					this.Onnvc_FromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_OrderNumber", DbType="NVarChar(50)")]
		public string nvc_OrderNumber
		{
			get
			{
				return this._nvc_OrderNumber;
			}
			set
			{
				if ((this._nvc_OrderNumber != value))
				{
					this.Onnvc_OrderNumberChanging(value);
					this.SendPropertyChanging();
					this._nvc_OrderNumber = value;
					this.SendPropertyChanged("nvc_OrderNumber");
					this.Onnvc_OrderNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_OnlineMessage")]
	public partial class t_OnlineMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_Id;
		
		private string _nvc_AdvisoryContent;
		
		private int _i_MemberId;
		
		private System.Nullable<System.DateTime> _dt_AddTime;
		
		private int _i_Replay;
		
		private string _nvc_ReplayContent;
		
		private int _i_ManagerId;
		
		private System.Nullable<System.DateTime> _dt_ReplayTime;
		
		private string _nvc_Email;
		
		private string _nvc_SubTitle;
		
		private int _i_IsTop;
		
		private int _i_IsRecommend;
		
		private string _nvc_Language;
		
		private System.Nullable<int> _i_weizhi;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IdChanging(int value);
    partial void Oni_IdChanged();
    partial void Onnvc_AdvisoryContentChanging(string value);
    partial void Onnvc_AdvisoryContentChanged();
    partial void Oni_MemberIdChanging(int value);
    partial void Oni_MemberIdChanged();
    partial void Ondt_AddTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_AddTimeChanged();
    partial void Oni_ReplayChanging(int value);
    partial void Oni_ReplayChanged();
    partial void Onnvc_ReplayContentChanging(string value);
    partial void Onnvc_ReplayContentChanged();
    partial void Oni_ManagerIdChanging(int value);
    partial void Oni_ManagerIdChanged();
    partial void Ondt_ReplayTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondt_ReplayTimeChanged();
    partial void Onnvc_EmailChanging(string value);
    partial void Onnvc_EmailChanged();
    partial void Onnvc_SubTitleChanging(string value);
    partial void Onnvc_SubTitleChanged();
    partial void Oni_IsTopChanging(int value);
    partial void Oni_IsTopChanged();
    partial void Oni_IsRecommendChanging(int value);
    partial void Oni_IsRecommendChanged();
    partial void Onnvc_LanguageChanging(string value);
    partial void Onnvc_LanguageChanged();
    partial void Oni_weizhiChanging(System.Nullable<int> value);
    partial void Oni_weizhiChanged();
    #endregion
		
		public t_OnlineMessage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_Id
		{
			get
			{
				return this._i_Id;
			}
			set
			{
				if ((this._i_Id != value))
				{
					this.Oni_IdChanging(value);
					this.SendPropertyChanging();
					this._i_Id = value;
					this.SendPropertyChanged("i_Id");
					this.Oni_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_AdvisoryContent", DbType="NVarChar(500)")]
		public string nvc_AdvisoryContent
		{
			get
			{
				return this._nvc_AdvisoryContent;
			}
			set
			{
				if ((this._nvc_AdvisoryContent != value))
				{
					this.Onnvc_AdvisoryContentChanging(value);
					this.SendPropertyChanging();
					this._nvc_AdvisoryContent = value;
					this.SendPropertyChanged("nvc_AdvisoryContent");
					this.Onnvc_AdvisoryContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_MemberId", DbType="Int NOT NULL")]
		public int i_MemberId
		{
			get
			{
				return this._i_MemberId;
			}
			set
			{
				if ((this._i_MemberId != value))
				{
					this.Oni_MemberIdChanging(value);
					this.SendPropertyChanging();
					this._i_MemberId = value;
					this.SendPropertyChanged("i_MemberId");
					this.Oni_MemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_AddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_AddTime
		{
			get
			{
				return this._dt_AddTime;
			}
			set
			{
				if ((this._dt_AddTime != value))
				{
					this.Ondt_AddTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_AddTime = value;
					this.SendPropertyChanged("dt_AddTime");
					this.Ondt_AddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Replay", DbType="Int NOT NULL")]
		public int i_Replay
		{
			get
			{
				return this._i_Replay;
			}
			set
			{
				if ((this._i_Replay != value))
				{
					this.Oni_ReplayChanging(value);
					this.SendPropertyChanging();
					this._i_Replay = value;
					this.SendPropertyChanged("i_Replay");
					this.Oni_ReplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_ReplayContent", DbType="NVarChar(MAX)")]
		public string nvc_ReplayContent
		{
			get
			{
				return this._nvc_ReplayContent;
			}
			set
			{
				if ((this._nvc_ReplayContent != value))
				{
					this.Onnvc_ReplayContentChanging(value);
					this.SendPropertyChanging();
					this._nvc_ReplayContent = value;
					this.SendPropertyChanged("nvc_ReplayContent");
					this.Onnvc_ReplayContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ManagerId", DbType="Int NOT NULL")]
		public int i_ManagerId
		{
			get
			{
				return this._i_ManagerId;
			}
			set
			{
				if ((this._i_ManagerId != value))
				{
					this.Oni_ManagerIdChanging(value);
					this.SendPropertyChanging();
					this._i_ManagerId = value;
					this.SendPropertyChanged("i_ManagerId");
					this.Oni_ManagerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt_ReplayTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt_ReplayTime
		{
			get
			{
				return this._dt_ReplayTime;
			}
			set
			{
				if ((this._dt_ReplayTime != value))
				{
					this.Ondt_ReplayTimeChanging(value);
					this.SendPropertyChanging();
					this._dt_ReplayTime = value;
					this.SendPropertyChanged("dt_ReplayTime");
					this.Ondt_ReplayTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Email", DbType="NVarChar(250)")]
		public string nvc_Email
		{
			get
			{
				return this._nvc_Email;
			}
			set
			{
				if ((this._nvc_Email != value))
				{
					this.Onnvc_EmailChanging(value);
					this.SendPropertyChanging();
					this._nvc_Email = value;
					this.SendPropertyChanged("nvc_Email");
					this.Onnvc_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_SubTitle", DbType="NVarChar(500)")]
		public string nvc_SubTitle
		{
			get
			{
				return this._nvc_SubTitle;
			}
			set
			{
				if ((this._nvc_SubTitle != value))
				{
					this.Onnvc_SubTitleChanging(value);
					this.SendPropertyChanging();
					this._nvc_SubTitle = value;
					this.SendPropertyChanged("nvc_SubTitle");
					this.Onnvc_SubTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IsTop", DbType="Int NOT NULL")]
		public int i_IsTop
		{
			get
			{
				return this._i_IsTop;
			}
			set
			{
				if ((this._i_IsTop != value))
				{
					this.Oni_IsTopChanging(value);
					this.SendPropertyChanging();
					this._i_IsTop = value;
					this.SendPropertyChanged("i_IsTop");
					this.Oni_IsTopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_IsRecommend", DbType="Int NOT NULL")]
		public int i_IsRecommend
		{
			get
			{
				return this._i_IsRecommend;
			}
			set
			{
				if ((this._i_IsRecommend != value))
				{
					this.Oni_IsRecommendChanging(value);
					this.SendPropertyChanging();
					this._i_IsRecommend = value;
					this.SendPropertyChanged("i_IsRecommend");
					this.Oni_IsRecommendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvc_Language", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string nvc_Language
		{
			get
			{
				return this._nvc_Language;
			}
			set
			{
				if ((this._nvc_Language != value))
				{
					this.Onnvc_LanguageChanging(value);
					this.SendPropertyChanging();
					this._nvc_Language = value;
					this.SendPropertyChanged("nvc_Language");
					this.Onnvc_LanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_weizhi", DbType="Int")]
		public System.Nullable<int> i_weizhi
		{
			get
			{
				return this._i_weizhi;
			}
			set
			{
				if ((this._i_weizhi != value))
				{
					this.Oni_weizhiChanging(value);
					this.SendPropertyChanging();
					this._i_weizhi = value;
					this.SendPropertyChanged("i_weizhi");
					this.Oni_weizhiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
